import { useEffect, useState } from 'react'
import Taro, { useDidShow, useRouter } from '@tarojs/taro'
import { Picker, Text, View } from '@tarojs/components'
import { get, money, request, type Address } from '../../api'
type Quote={quoteHash:string;itemAmountFen:number;shippingAmountFen:number;payableAmountFen:number;purchasable:boolean;reasons:string[];items:{productTitle:string;quantity:number;lineAmountFen:number;reason?:string}[];groups:{supplierName:string;originLabel:string;billableWeightG:number;shippingFeeFen?:number;reason?:string}[]}
export default function Checkout(){const {params}=useRouter();const ids=(params.ids||'').split(',').map(Number).filter(Boolean);const [addresses,setAddresses]=useState<Address[]>([]);const [addressId,setAddressId]=useState<number>();const [quote,setQuote]=useState<Quote>();
  useDidShow(()=>{get<Address[]>('/api/customer/addresses').then(a=>{setAddresses(a);setAddressId(current=>a.some(x=>x.id===current)?current:(a.find(x=>x.isDefault)||a[0])?.id)}).catch(e=>Taro.showToast({title:e.message,icon:'none'}))})
  useEffect(()=>{if(addressId)request<Quote>('/api/customer/checkout/quote','POST',{addressId,cartItemIds:ids}).then(setQuote).catch(e=>Taro.showToast({title:e.message,icon:'none'}))},[addressId])
  if(!addresses.length)return <View className="page"><Text className="empty">请先添加收货地址</Text><View className="primary-button" onClick={()=>Taro.navigateTo({url:'/pages/addresses/index'})}>管理地址</View></View>
  return <View className="page"><Text className="heading">确认订单</Text><Picker mode="selector" range={addresses.map(a=>`${a.recipient} ${a.provinceName}${a.cityName}${a.districtName}`)} onChange={e=>setAddressId(addresses[Number(e.detail.value)].id)}><View className="panel">收货地址：{addresses.find(a=>a.id===addressId)?.recipient}　{addresses.find(a=>a.id===addressId)?.detail}</View></Picker>
    {quote?.items.map((i,n)=><View className="line" key={n}><Text>{i.productTitle} × {i.quantity}</Text><Text>{money(i.lineAmountFen)}</Text></View>)}{quote?.groups.map((g,n)=><View className="panel" key={n}><Text>{g.supplierName} · {g.originLabel}</Text><Text className="subtle">计费重量 {g.billableWeightG} 克，运费 {g.shippingFeeFen==null?'不可配送':money(g.shippingFeeFen)}</Text>{g.reason&&<Text className="error">{g.reason}</Text>}</View>)}
    {quote?.reasons.map((r,n)=><Text className="error" key={n}>{r}</Text>)}<View className="line"><Text>商品</Text><Text>{money(quote?.itemAmountFen||0)}</Text></View><View className="line"><Text>运费</Text><Text>{money(quote?.shippingAmountFen||0)}</Text></View><View className="line"><Text>应付</Text><Text className="total">{money(quote?.payableAmountFen||0)}</Text></View>
    <Text className="note">提交后只创建待支付订单并预占库存。开发模拟支付入口仅在订单详情且明确开启时显示；真实支付尚未接入。</Text><View className="primary-button" onClick={async()=>{if(!quote?.purchasable||!addressId)return Taro.showToast({title:'当前订单不可提交',icon:'none'});try{const o=await request<{order:{id:number}}>('/api/customer/orders','POST',{addressId,cartItemIds:ids,quoteHash:quote.quoteHash,idempotencyKey:`mini_${Date.now()}_${Math.random().toString(36).slice(2,10)}`});Taro.redirectTo({url:`/pages/order-detail/index?id=${o.order.id}`})}catch(e){Taro.showToast({title:(e as Error).message,icon:'none'});if((e as Error).message.includes('changed'))setQuote(undefined)}}}>创建待支付订单</View>
  </View>}
