import { useRef, useState } from 'react'
import Taro, { useDidShow, useRouter } from '@tarojs/taro'
import { Picker, Text, View } from '@tarojs/components'
import { get, money, newCheckoutAddressKey, request, type Address } from '../../api'
type Quote={quoteHash:string;itemAmountFen:number;shippingAmountFen:number;payableAmountFen:number;purchasable:boolean;reasons:string[];items:{productTitle:string;quantity:number;lineAmountFen:number;reason?:string}[];groups:{supplierName:string;originLabel:string;billableWeightG:number;shippingFeeFen?:number;reason?:string}[]}
export default function Checkout(){const {params}=useRouter();const ids=(params.ids||'').split(',').map(Number).filter(Boolean);const [addresses,setAddresses]=useState<Address[]>([]);const [addressId,setAddressId]=useState<number>();const [quote,setQuote]=useState<Quote>();const [quoteError,setQuoteError]=useState('');
  const chosen=useRef<number>();chosen.current=addressId
  const quoteSequence=useRef(0)
  const refreshQuote=(id?:number)=>{const sequence=++quoteSequence.current;setQuote(undefined);setQuoteError('');if(id)request<Quote>('/api/customer/checkout/quote','POST',{addressId:id,cartItemIds:ids}).then(result=>{if(sequence===quoteSequence.current)setQuote(result)}).catch(e=>{if(sequence===quoteSequence.current)setQuoteError((e as Error).message||'运费试算失败，请重试')})}
  useDidShow(()=>{get<Address[]>('/api/customer/addresses').then(a=>{setAddresses(a);const created=Number(Taro.getStorageSync(newCheckoutAddressKey));Taro.removeStorageSync(newCheckoutAddressKey);const next=a.some(x=>x.id===created)?created:a.some(x=>x.id===chosen.current)?chosen.current:(a.find(x=>x.isDefault)||a[0])?.id;setAddressId(next);refreshQuote(next)}).catch(e=>Taro.showToast({title:e.message,icon:'none'}))})
  if(!addresses.length)return <View className="page"><Text className="empty">请先添加收货地址</Text><View className="primary-button" onClick={()=>Taro.navigateTo({url:'/pages/addresses/index?from=checkout'})}>新增地址</View></View>
  return <View className="page"><Text className="heading">确认订单</Text><Picker mode="selector" range={addresses.map(a=>`${a.recipient} ${a.provinceName}${a.cityName}${a.districtName}`)} onChange={e=>{const next=addresses[Number(e.detail.value)]?.id;setAddressId(next);refreshQuote(next)}}><View className="panel">收货地址：{addresses.find(a=>a.id===addressId)?.recipient}　{addresses.find(a=>a.id===addressId)?.detail}</View></Picker><View className="secondary-button" onClick={()=>Taro.navigateTo({url:'/pages/addresses/index?from=checkout'})}>新增收货地址</View>
    {quote?.items.map((i,n)=><View className="line" key={n}><Text>{i.productTitle} × {i.quantity}</Text><Text>{money(i.lineAmountFen)}</Text></View>)}{quote?.groups.map((g,n)=><View className="panel" key={n}><Text>{g.supplierName} · {g.originLabel}</Text><Text className="subtle">计费重量 {g.billableWeightG} 克，运费 {g.shippingFeeFen==null?'不可配送':money(g.shippingFeeFen)}</Text>{g.reason&&<Text className="error">{g.reason}</Text>}</View>)}
    {quote?.reasons.map((r,n)=><Text className="error" key={n}>{r}</Text>)}{quoteError&&<View><Text className="error">{quoteError}</Text><View className="secondary-button" onClick={()=>refreshQuote(addressId)}>重试运费试算</View></View>}{!quote&&!quoteError&&<Text className="subtle">运费试算中…</Text>}{quote&&<><View className="line"><Text>商品</Text><Text>{money(quote.itemAmountFen)}</Text></View><View className="line"><Text>运费</Text><Text>{money(quote.shippingAmountFen)}</Text></View><View className="line"><Text>应付</Text><Text className="total">{money(quote.payableAmountFen)}</Text></View></>}
    <Text className="note">提交后只创建待支付订单并预占库存。{DEV_LOGIN_ENABLED ? '开发模拟支付入口仅在订单详情且明确开启时显示；真实支付尚未接入。' : '真实支付尚未接入。'}</Text><View className="primary-button" onClick={async()=>{if(!quote?.purchasable||!addressId)return Taro.showToast({title:'当前订单不可提交',icon:'none'});try{const o=await request<{order:{id:number}}>('/api/customer/orders','POST',{addressId,cartItemIds:ids,quoteHash:quote.quoteHash,idempotencyKey:`mini_${Date.now()}_${Math.random().toString(36).slice(2,10)}`});Taro.redirectTo({url:`/pages/order-detail/index?id=${o.order.id}`})}catch(e){Taro.showToast({title:(e as Error).message,icon:'none'});if((e as Error).message.includes('changed'))setQuote(undefined)}}}>创建待支付订单</View>
  </View>}
