package com.orchard.mall;

import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@Service
public class AfterSalesService {
    private final JdbcTemplate db;public AfterSalesService(JdbcTemplate db){this.db=db;}
    public record ApplyItem(@Positive long orderItemId,@Positive int quantity){}
    public record ApplyRequest(@Pattern(regexp="REFUND|REPLACEMENT") String action,@NotBlank @Size(max=40) String reasonCode,@Size(max=500) String reasonDetail,@NotEmpty @Size(max=20) List<ApplyItem> items,@Positive Long requestedRefundFen){}
    public record ReviewItem(@Positive long afterSaleItemId,@Positive int approvedQuantity){}
    public record ReviewRequest(@Pattern(regexp="APPROVE|REJECT") String decision,@Size(max=500) String comment,
        @PositiveOrZero Long refundAmountFen,@PositiveOrZero Long shippingRefundFen,
        @Pattern(regexp="MERCHANT|SUPPLIER|SHARED") String responsibility,@PositiveOrZero Long supplierDeductionFen,
        @Pattern(regexp="DEV_SIMULATOR|WECHAT|ALIPAY") String refundChannel,List<ReviewItem> items){}
    private long insert(String sql,Object... args){var k=new GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement(sql,new String[]{"id"});for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},k);return k.getKey().longValue();}
    private long goodsRemaining(long orderId){
        long paid=db.queryForObject("SELECT item_amount_fen FROM sales_order WHERE id=?",Long.class,orderId);
        long occupied=db.queryForObject("SELECT COALESCE(SUM(r.amount_fen-r.shipping_amount_fen),0) FROM refund_order r JOIN after_sale_case c ON c.id=r.after_sale_case_id WHERE c.sales_order_id=? AND r.status IN ('CREATED','PENDING','PROCESSING','UNKNOWN','SUCCEEDED')",Long.class,orderId);
        return Math.max(0,paid-occupied);
    }
    public Map<String,Object> eligibility(long consumer,long orderId,long orderItemId){
        var rows=db.query("SELECT o.status,o.item_amount_fen,i.quantity,i.unit_price_fen FROM sales_order o JOIN order_item i ON i.order_id=o.id WHERE o.id=? AND o.consumer_id=? AND i.id=?",(rs,n)->new Object[]{rs.getString(1),rs.getLong(2),rs.getInt(3),rs.getLong(4)},orderId,consumer,orderItemId);
        if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        var x=rows.getFirst();int already=db.queryForObject("SELECT COALESCE(SUM(ai.requested_qty),0) FROM after_sale_item ai JOIN after_sale_case c ON c.id=ai.case_id WHERE ai.order_item_id=? AND c.status NOT IN ('REJECTED','CANCELLED')",Integer.class,orderItemId);
        int remainingQty=Math.max(0,(int)x[2]-already);long max="PAID".equals(x[0])?Math.min(Math.multiplyExact((long)remainingQty,(long)x[3]),goodsRemaining(orderId)):0;
        String reason=!"PAID".equals(x[0])?"订单尚未支付，不能申请售后":remainingQty==0?"该商品已申请过售后；当前每件商品仅支持一次售后申请":max==0?"商品可退金额已用尽":"";
        String contact=db.queryForObject("SELECT COALESCE(contact_phone,'') FROM store_settings WHERE id=1",String.class);
        return Map.of("remainingQty",remainingQty,"unitPaidFen",x[3],"maxRefundFen",max,"reason",reason,"storeContactPhone",contact);
    }
    @Transactional public Map<String,Object> apply(long consumer,long orderId,ApplyRequest r){
        var orders=db.query("SELECT status FROM sales_order WHERE id=? AND consumer_id=? FOR UPDATE",(rs,n)->rs.getString(1),orderId,consumer);if(orders.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);if(!"PAID".equals(orders.getFirst()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Only paid orders support after-sales");
        if("REPLACEMENT".equals(r.action())&&r.items().size()!=1)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"The first replacement version supports one order item per case");
        var requested=new TreeMap<Long,Integer>();for(var line:r.items())requested.merge(line.orderItemId(),line.quantity(),Math::addExact);
        long maxRefund=0;var snapshots=new ArrayList<long[]>();
        for(var e:requested.entrySet()){
            var rows=db.query("SELECT i.id,i.quantity,i.unit_price_fen,i.supply_id,ti.id,ti.required_qty,ti.shipped_qty,ti.frozen_qty,ti.cancelled_qty,t.id FROM order_item i JOIN fulfillment_task_item ti ON ti.order_item_id=i.id JOIN fulfillment_task t ON t.id=ti.task_id AND t.task_type='ORIGINAL' WHERE i.id=? AND i.order_id=? FOR UPDATE",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2),rs.getLong(3),rs.getLong(4),rs.getLong(5),rs.getLong(6),rs.getLong(7),rs.getLong(8),rs.getLong(9),rs.getLong(10)},e.getKey(),orderId);
            if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Order item is not fulfillable");var x=rows.getFirst();
            int already=db.queryForObject("SELECT COALESCE(SUM(ai.requested_qty),0) FROM after_sale_item ai JOIN after_sale_case c ON c.id=ai.case_id WHERE ai.order_item_id=? AND c.status NOT IN ('REJECTED','CANCELLED')",Integer.class,e.getKey());
            if(e.getValue()+already>x[1])throw new ResponseStatusException(HttpStatus.CONFLICT,"After-sales quantity exceeds purchased quantity");
            int availableUnshipped=(int)(x[5]-x[6]-x[7]-x[8]);int freeze="REFUND".equals(r.action())?Math.min(e.getValue(),Math.max(0,availableUnshipped)):0;
            if(freeze>0)db.update("UPDATE fulfillment_task_item SET frozen_qty=frozen_qty+? WHERE id=? AND shipped_qty+frozen_qty+cancelled_qty+?<=required_qty",freeze,x[4],freeze);
            snapshots.add(new long[]{x[0],x[4],e.getValue(),freeze,x[2],x[3]});maxRefund=Math.addExact(maxRefund,Math.multiplyExact(x[2],e.getValue()));
        }
        if(r.requestedRefundFen()!=null&&!"REFUND".equals(r.action()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only refund applications may specify an amount");
        if(r.requestedRefundFen()!=null&&r.requestedRefundFen()<=0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Requested refund must be positive");
        if("REFUND".equals(r.action()))maxRefund=Math.min(maxRefund,goodsRemaining(orderId));
        if("REFUND".equals(r.action())&&maxRefund<=0)throw new ResponseStatusException(HttpStatus.CONFLICT,"No refundable item amount remains");
        if(r.requestedRefundFen()!=null&&r.requestedRefundFen()>maxRefund)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Requested refund exceeds current refundable item amount");
        long requestedRefund=r.requestedRefundFen()==null?maxRefund:r.requestedRefundFen();
        long caseId=insert("INSERT INTO after_sale_case(case_no,sales_order_id,consumer_id,requested_action,reason_code,reason_detail,status,requested_refund_fen) VALUES (?,?,?,?,?,?,'SUBMITTED',?)","AS"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT),orderId,consumer,r.action(),r.reasonCode(),r.reasonDetail(),requestedRefund);
        for(var x:snapshots)db.update("INSERT INTO after_sale_item(case_id,order_item_id,task_item_id,requested_qty,frozen_qty,unit_paid_fen) VALUES (?,?,?,?,?,?)",caseId,x[0],x[1],x[2],x[3],x[4]);
        for(var x:snapshots)db.update("UPDATE supplier_ledger_entry SET status='FROZEN',available_at=NULL WHERE source_key=? AND status='AVAILABLE'","goods:"+x[0]);
        db.update("INSERT INTO after_sale_operation(case_id,operation,detail,actor_type,actor) VALUES (?,'SUBMIT',?,'CUSTOMER',?)",caseId,r.reasonCode(),"consumer:"+consumer);
        db.update("UPDATE sales_order SET after_sales_status='OPEN' WHERE id=?",orderId);return detail(caseId,consumer,false,null);
    }
    public List<Map<String,Object>> customerList(long consumer){return list(" WHERE c.consumer_id=?",consumer);}
    public List<Map<String,Object>> adminList(){return list("",new Object[]{});}
    public List<Map<String,Object>> supplierList(long supplier){return list(" WHERE EXISTS(SELECT 1 FROM after_sale_item ai JOIN order_item oi ON oi.id=ai.order_item_id WHERE ai.case_id=c.id AND oi.supplier_id=?)",supplier);}
    private List<Map<String,Object>> list(String where,Object... args){return db.query("SELECT c.id,c.case_no,o.order_no,c.requested_action,c.reason_code,c.status,c.requested_refund_fen,c.approved_refund_fen,c.created_at FROM after_sale_case c JOIN sales_order o ON o.id=c.sales_order_id"+where+" ORDER BY c.id DESC",(rs,n)->Map.of("id",rs.getLong(1),"caseNo",rs.getString(2),"orderNo",rs.getString(3),"action",rs.getString(4),"reasonCode",rs.getString(5),"status",rs.getString(6),"requestedRefundFen",rs.getLong(7),"approvedRefundFen",rs.getLong(8),"createdAt",rs.getTimestamp(9).toLocalDateTime().toString()),args);}
    public Map<String,Object> detail(long id,Long consumer,boolean admin,Long supplier){
        String scope=admin?"":consumer!=null?" AND c.consumer_id=?":" AND EXISTS(SELECT 1 FROM after_sale_item ax JOIN order_item ox ON ox.id=ax.order_item_id WHERE ax.case_id=c.id AND ox.supplier_id=?)";Object[] args=admin?new Object[]{id}:new Object[]{id,consumer!=null?consumer:supplier};
        var rows=db.query("SELECT c.id,c.case_no,c.sales_order_id,o.order_no,c.requested_action,c.reason_code,c.reason_detail,c.status,c.review_comment,c.responsibility,c.requested_refund_fen,c.approved_refund_fen,c.created_at FROM after_sale_case c JOIN sales_order o ON o.id=c.sales_order_id WHERE c.id=?"+scope,(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getLong(1));m.put("caseNo",rs.getString(2));m.put("orderId",rs.getLong(3));m.put("orderNo",rs.getString(4));m.put("action",rs.getString(5));m.put("reasonCode",rs.getString(6));m.put("reasonDetail",rs.getString(7));m.put("status",rs.getString(8));m.put("reviewComment",rs.getString(9));m.put("responsibility",rs.getString(10));m.put("requestedRefundFen",rs.getLong(11));m.put("approvedRefundFen",rs.getLong(12));m.put("createdAt",rs.getTimestamp(13).toLocalDateTime().toString());return m;},args);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var result=rows.getFirst();
        result.put("items",db.query("SELECT ai.id,ai.order_item_id,oi.product_title,oi.sku_code,ai.requested_qty,ai.frozen_qty,ai.approved_qty,ai.unit_paid_fen,ai.status FROM after_sale_item ai JOIN order_item oi ON oi.id=ai.order_item_id WHERE ai.case_id=? ORDER BY ai.id",(rs,n)->Map.of("id",rs.getLong(1),"orderItemId",rs.getLong(2),"productTitle",rs.getString(3),"skuCode",rs.getString(4),"requestedQty",rs.getInt(5),"frozenQty",rs.getInt(6),"approvedQty",rs.getInt(7),"unitPaidFen",rs.getLong(8),"status",rs.getString(9)),id));
        result.put("evidence",db.query("SELECT id,content_type,size_bytes,created_at FROM after_sale_evidence WHERE case_id=? ORDER BY id",(rs,n)->Map.of("id",rs.getLong(1),"contentType",rs.getString(2),"sizeBytes",rs.getLong(3),"createdAt",rs.getTimestamp(4).toLocalDateTime().toString()),id));result.put("refunds",db.query("SELECT r.id,r.refund_no,r.amount_fen,r.status,r.created_at,(SELECT a.attempt_no FROM refund_attempt a WHERE a.refund_order_id=r.id ORDER BY a.id DESC LIMIT 1),(SELECT a.channel FROM refund_attempt a WHERE a.refund_order_id=r.id ORDER BY a.id DESC LIMIT 1) FROM refund_order r WHERE r.after_sale_case_id=?",(rs,n)->Map.of("id",rs.getLong(1),"refundNo",rs.getString(2),"amountFen",rs.getLong(3),"status",rs.getString(4),"createdAt",rs.getTimestamp(5).toLocalDateTime().toString(),"attemptNo",rs.getString(6),"channel",rs.getString(7)),id));result.put("replacementTasks",db.query("SELECT id,task_no,status FROM fulfillment_task WHERE source_key=?",(rs,n)->Map.of("id",rs.getLong(1),"taskNo",rs.getString(2),"status",rs.getString(3)),"AFTER_SALE:"+id));return result;
    }
    public record ReviewOutcome(long caseId,String action,String status,long refundAmountFen,long shippingRefundFen,String reason){}
    @Transactional public ReviewOutcome review(long caseId,String actor,ReviewRequest r){
        var cases=db.query("SELECT sales_order_id,requested_action,status,requested_refund_fen FROM after_sale_case WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2),rs.getString(3),rs.getLong(4)},caseId);if(cases.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var c=cases.getFirst();if(!List.of("SUBMITTED","WAITING_STOCK").contains(c[2]))throw new ResponseStatusException(HttpStatus.CONFLICT,"Case is not reviewable");long orderId=(long)c[0];db.queryForList("SELECT id FROM sales_order WHERE id=? FOR UPDATE",orderId);
        var items=db.query("SELECT ai.id,ai.order_item_id,ai.task_item_id,ai.requested_qty,ai.frozen_qty,ai.unit_paid_fen,oi.supply_id,oi.supplier_id,oi.group_id,oi.supply_price_fen FROM after_sale_item ai JOIN order_item oi ON oi.id=ai.order_item_id WHERE ai.case_id=? ORDER BY ai.task_item_id FOR UPDATE",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2),rs.getLong(3),rs.getLong(4),rs.getLong(5),rs.getLong(6),rs.getLong(7),rs.getLong(8),rs.getLong(9),rs.getLong(10)},caseId);
        if("REJECT".equals(r.decision())){for(var x:items)if(x[4]>0)db.update("UPDATE fulfillment_task_item SET frozen_qty=frozen_qty-? WHERE id=? AND frozen_qty>=?",x[4],x[2],x[4]);db.update("UPDATE after_sale_case SET status='REJECTED',review_comment=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",r.comment(),caseId);db.update("UPDATE after_sale_item SET status='REJECTED',frozen_qty=0 WHERE case_id=?",caseId);operation(caseId,"REJECT",r.comment(),"ADMIN",actor);refreshOrderAfterSales(orderId);refreshFulfillmentAndLedger(orderId);return new ReviewOutcome(caseId,(String)c[1],"REJECTED",0,0,null);}
        var approved=new HashMap<Long,Integer>();if(r.items()!=null)for(var x:r.items())approved.put(x.afterSaleItemId(),x.approvedQuantity());long max=0;
        for(var x:items){int qty=approved.getOrDefault(x[0],(int)x[3]);if(qty<1||qty>x[3])throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid approved quantity");max=Math.addExact(max,Math.multiplyExact(x[5],qty));db.update("UPDATE after_sale_item SET approved_qty=?,status='APPROVED' WHERE id=?",qty,x[0]);}
        String responsibility=r.responsibility()==null?"MERCHANT":r.responsibility();long deduction=r.supplierDeductionFen()==null?0:r.supplierDeductionFen();
        if("REFUND".equals(c[1])){
            long refund=r.refundAmountFen()==null?max:r.refundAmountFen();long shipping=r.shippingRefundFen()==null?0:r.shippingRefundFen();
            long occupiedShipping=db.queryForObject("SELECT COALESCE(SUM(r.shipping_amount_fen),0) FROM refund_order r JOIN after_sale_case c2 ON c2.id=r.after_sale_case_id WHERE c2.sales_order_id=? AND r.status IN ('CREATED','PENDING','PROCESSING','UNKNOWN','SUCCEEDED')",Long.class,orderId);
            long shippingPaid=db.queryForObject("SELECT shipping_amount_fen FROM sales_order WHERE id=?",Long.class,orderId);
            long collected=db.queryForObject("SELECT amount_fen FROM payment_order WHERE sales_order_id=?",Long.class,orderId);
            long occupiedTotal=db.queryForObject("SELECT COALESCE(SUM(r.amount_fen),0) FROM refund_order r WHERE r.payment_order_id=(SELECT id FROM payment_order WHERE sales_order_id=?) AND r.status IN ('CREATED','PENDING','PROCESSING','UNKNOWN','SUCCEEDED')",Long.class,orderId);
            if(refund<=0||shipping>refund||refund>max+shipping||refund>(long)c[3]||refund-shipping>goodsRemaining(orderId)||shipping>shippingPaid-occupiedShipping||refund>collected-occupiedTotal)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Refund exceeds application or current refundable balance");
            for(var x:items){int qty=approved.getOrDefault(x[0],(int)x[3]);int cancel=Math.min(qty,(int)x[4]);if(db.update("UPDATE fulfillment_task_item SET frozen_qty=frozen_qty-?,cancelled_qty=cancelled_qty+? WHERE id=? AND frozen_qty>=?",x[4],cancel,x[2],x[4])!=1)throw new ResponseStatusException(HttpStatus.CONFLICT,"Frozen shipment quantity changed");if(cancel>0){db.update("UPDATE supply_inventory SET on_hand_qty=on_hand_qty+? WHERE supply_id=?",cancel,x[6]);db.update("INSERT INTO inventory_movement(supply_id,order_id,delta_on_hand,delta_reserved,reason,actor) VALUES (?,?,?,0,'未发货售后取消恢复库存',?)",x[6],orderId,cancel,actor);db.update("UPDATE supplier_ledger_entry SET quantity=quantity-?,amount_fen=amount_fen-? WHERE source_key=? AND status='FROZEN'",cancel,Math.multiplyExact(x[9],cancel),"goods:"+x[1]);}db.update("UPDATE after_sale_item SET frozen_qty=0 WHERE id=?",x[0]);}
            db.update("UPDATE after_sale_case SET status='REFUND_PENDING',review_comment=?,responsibility=?,approved_refund_fen=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",r.comment(),responsibility,refund,caseId);if(deduction>0)ledgerDeduction(items.getFirst()[7],orderId,caseId,deduction,responsibility,actor);operation(caseId,"APPROVE_REFUND","refund="+refund+", releasedFreeze="+items.stream().mapToLong(x->x[4]).sum(),"ADMIN",actor);refreshFulfillmentAndLedger(orderId);return new ReviewOutcome(caseId,"REFUND","REFUND_PENDING",refund,shipping,null);
        }
        if(items.size()!=1)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Replacement supports one item");var x=items.getFirst();int qty=approved.getOrDefault(x[0],(int)x[3]);
        Integer sourceActive=db.queryForObject("SELECT COUNT(*) FROM sku_supply s JOIN supplier v ON v.id=s.supplier_id AND v.enabled=TRUE JOIN origin o ON o.id=s.origin_id AND o.enabled=TRUE WHERE s.id=?",Integer.class,x[6]);
        if(sourceActive==null||sourceActive==0){String reason="原订单供货来源或发货地已停用，需人工处理；未自动切换供应商";db.update("UPDATE after_sale_case SET status='WAITING_STOCK',review_comment=?,responsibility=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",r.comment(),responsibility,caseId);operation(caseId,"WAITING_SOURCE",reason,"ADMIN",actor);return new ReviewOutcome(caseId,"REPLACEMENT","WAITING_STOCK",0,0,reason);}
        if(db.update("UPDATE supply_inventory SET reserved_qty=reserved_qty+? WHERE supply_id=? AND on_hand_qty-reserved_qty>=?",qty,x[6],qty)!=1){String reason="原供货来源库存不足，补发等待人工处理";db.update("UPDATE after_sale_case SET status='WAITING_STOCK',review_comment=?,responsibility=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",r.comment(),responsibility,caseId);operation(caseId,"WAITING_STOCK",reason,"ADMIN",actor);return new ReviewOutcome(caseId,"REPLACEMENT","WAITING_STOCK",0,0,reason);}
        long groupId=cloneGroup(x[8],orderId);long taskId=insert("INSERT INTO fulfillment_task(task_no,sales_order_id,order_group_id,supplier_id,status,task_type,source_key) VALUES (?,?,?,?,'PENDING_ACCEPTANCE','REPLACEMENT',?)","REP"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT),orderId,groupId,x[7],"AFTER_SALE:"+caseId);insert("INSERT INTO fulfillment_task_item(task_id,order_item_id,product_title,sku_code,spec_json,required_qty) SELECT ?,id,product_title,sku_code,spec_json,? FROM order_item WHERE id=?",taskId,qty,x[1]);db.update("INSERT INTO replacement_reservation(after_sale_case_id,fulfillment_task_id,supply_id,quantity,status) VALUES (?,?,?,?,'HELD')",caseId,taskId,x[6],qty);db.update("INSERT INTO inventory_movement(supply_id,order_id,delta_on_hand,delta_reserved,reason,actor) VALUES (?,?,0,?,'补发库存预占',?)",x[6],orderId,qty,actor);
        db.update("UPDATE after_sale_case SET status='REPLACEMENT_PENDING',review_comment=?,responsibility=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?",r.comment(),responsibility,caseId);long replacementCost=Math.multiplyExact(x[9],qty);db.update("INSERT INTO supplier_ledger_entry(supplier_id,sales_order_id,order_item_id,after_sale_case_id,entry_type,source_key,quantity,amount_fen,status,description) VALUES (?,?,?,?, 'REPLACEMENT_COST',?,?,?,'AVAILABLE',?)",x[7],orderId,x[1],caseId,"replacement-cost:"+caseId,qty,"SUPPLIER".equals(responsibility)?-replacementCost:0,"补发成本，承担方:"+responsibility);operation(caseId,"APPROVE_REPLACEMENT","qty="+qty+", cost="+replacementCost,"ADMIN",actor);return new ReviewOutcome(caseId,"REPLACEMENT","REPLACEMENT_PENDING",0,0,null);
    }
    private long cloneGroup(long source,long orderId){var k=new GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement("INSERT INTO order_group(order_id,supplier_id,supplier_name,origin_id,origin_label,origin_province,origin_city,origin_address,origin_province_code,origin_city_code,origin_district_code,origin_district,origin_contact_name,origin_contact_phone,template_id,template_name,template_version,rule_region_code,billable_weight_g,item_amount_fen,shipping_fee_fen) SELECT ?,supplier_id,supplier_name,origin_id,origin_label,origin_province,origin_city,origin_address,origin_province_code,origin_city_code,origin_district_code,origin_district,origin_contact_name,origin_contact_phone,template_id,template_name,template_version,rule_region_code,0,0,0 FROM order_group WHERE id=?",new String[]{"id"});p.setLong(1,orderId);p.setLong(2,source);return p;},k);return k.getKey().longValue();}
    private void ledgerDeduction(long supplier,long order,long caseId,long amount,String responsibility,String actor){db.update("INSERT INTO supplier_ledger_entry(supplier_id,sales_order_id,after_sale_case_id,entry_type,source_key,amount_fen,status,description) VALUES (?,?,?,'AFTER_SALE_DEDUCTION',?,?,'AVAILABLE',?)",supplier,order,caseId,"after-sale-deduction:"+caseId,-amount,"售后扣款，责任:"+responsibility+"，确认人:"+actor);}
    private void operation(long id,String op,String detail,String type,String actor){db.update("INSERT INTO after_sale_operation(case_id,operation,detail,actor_type,actor) VALUES (?,?,?,?,?)",id,op,Objects.toString(detail,""),type,actor);}
    private void refreshOrderAfterSales(long orderId){int open=db.queryForObject("SELECT COUNT(*) FROM after_sale_case WHERE sales_order_id=? AND status NOT IN ('REJECTED','CANCELLED','COMPLETED')",Integer.class,orderId);int total=db.queryForObject("SELECT COUNT(*) FROM after_sale_case WHERE sales_order_id=?",Integer.class,orderId);db.update("UPDATE sales_order SET after_sales_status=? WHERE id=?",open==0?(total==0?"NONE":"CLOSED"):"OPEN",orderId);}
    private void refreshFulfillmentAndLedger(long orderId){
        var tasks=db.queryForList("SELECT id FROM fulfillment_task WHERE sales_order_id=? AND task_type='ORIGINAL' ORDER BY id",Long.class,orderId);
        for(long taskId:tasks){int remaining=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item WHERE task_id=? AND shipped_qty+cancelled_qty<required_qty",Integer.class,taskId);if(remaining==0)db.update("UPDATE fulfillment_task SET status='SHIPPED',shipped_at=COALESCE(shipped_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE id=?",taskId);}
        int open=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=? AND task_type='ORIGINAL' AND status<>'SHIPPED'",Integer.class,orderId);db.update("UPDATE sales_order SET fulfillment_status=? WHERE id=?",open==0?"SHIPPED":"PARTIALLY_SHIPPED",orderId);
        var lines=db.query("SELECT id,group_id FROM order_item WHERE order_id=? ORDER BY id",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2)},orderId);
        for(var line:lines){long item=line[0];long group=line[1];int effective=db.queryForObject("SELECT required_qty-cancelled_qty FROM fulfillment_task_item ti JOIN fulfillment_task t ON t.id=ti.task_id WHERE ti.order_item_id=? AND t.task_type='ORIGINAL'",Integer.class,item);int confirmed=db.queryForObject("SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel p ON p.id=pi.parcel_id JOIN fulfillment_task_item ti ON ti.id=pi.task_item_id JOIN fulfillment_task t ON t.id=ti.task_id WHERE ti.order_item_id=? AND t.task_type='ORIGINAL' AND p.received_at IS NOT NULL",Integer.class,item);int pending=db.queryForObject("SELECT COUNT(*) FROM after_sale_item ai JOIN after_sale_case c ON c.id=ai.case_id WHERE ai.order_item_id=? AND c.status NOT IN ('REJECTED','CANCELLED','COMPLETED')",Integer.class,item);if(confirmed>=effective&&pending==0)db.update("UPDATE supplier_ledger_entry SET status='AVAILABLE',available_at=CURRENT_TIMESTAMP WHERE source_key=? AND status='FROZEN'","goods:"+item);int groupPending=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item ti JOIN order_item oi ON oi.id=ti.order_item_id WHERE oi.group_id=? AND (SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel pp ON pp.id=pi.parcel_id WHERE pi.task_item_id=ti.id AND pp.received_at IS NOT NULL)<ti.required_qty-ti.cancelled_qty",Integer.class,group);if(groupPending==0)db.update("UPDATE supplier_ledger_entry SET status='AVAILABLE',available_at=CURRENT_TIMESTAMP WHERE source_key=? AND status='FROZEN'","shipping:"+group);}
        int incomplete=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item ti JOIN fulfillment_task t ON t.id=ti.task_id WHERE t.sales_order_id=? AND t.task_type='ORIGINAL' AND (SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel pp ON pp.id=pi.parcel_id WHERE pi.task_item_id=ti.id AND pp.received_at IS NOT NULL)<ti.required_qty-ti.cancelled_qty",Integer.class,orderId);if(incomplete==0)db.update("UPDATE sales_order SET completion_status='COMPLETED',completed_at=COALESCE(completed_at,CURRENT_TIMESTAMP) WHERE id=?",orderId);
    }
}
