package com.orchard.mall;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.*;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.core.io.InputStreamResource;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;
import java.util.concurrent.*;

@RestController
public class AfterSalesController {
    private final AfterSalesService service;private final RefundService refunds;private final RefundAdapters refundAdapters;private final FulfillmentService fulfillment;private final JdbcTemplate db;private final ObjectStorage storage;private final ObjectMapper json;
    public AfterSalesController(AfterSalesService service,RefundService refunds,RefundAdapters refundAdapters,FulfillmentService fulfillment,JdbcTemplate db,ObjectStorage storage,ObjectMapper json){this.service=service;this.refunds=refunds;this.refundAdapters=refundAdapters;this.fulfillment=fulfillment;this.db=db;this.storage=storage;this.json=json;}
    private long customer(Authentication a){return Long.parseLong(a.getName());}private long supplier(Authentication a){return fulfillment.supplierId(a.getName());}
    @PostMapping("/api/customer/orders/{orderId}/after-sales") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> apply(Authentication a,@PathVariable long orderId,@Valid @RequestBody AfterSalesService.ApplyRequest r){return service.apply(customer(a),orderId,r);}
    @GetMapping("/api/customer/orders/{orderId}/items/{orderItemId}/after-sales/eligibility") public Map<String,Object> eligibility(Authentication a,@PathVariable long orderId,@PathVariable long orderItemId){return service.eligibility(customer(a),orderId,orderItemId);}
    @GetMapping("/api/customer/after-sales") public List<Map<String,Object>> mine(Authentication a){return service.customerList(customer(a));}
    @GetMapping("/api/customer/after-sales/{id}") public Map<String,Object> mineDetail(Authentication a,@PathVariable long id){return service.detail(id,customer(a),false,null);}
    @GetMapping("/api/admin/after-sales") public List<Map<String,Object>> admin(){return service.adminList();}
    @GetMapping("/api/admin/after-sales/{id}") public Map<String,Object> adminDetail(@PathVariable long id){return service.detail(id,null,true,null);}
    @PostMapping("/api/admin/after-sales/{id}/review") public Map<String,Object> review(Authentication a,@PathVariable long id,@Valid @RequestBody AfterSalesService.ReviewRequest r){if("APPROVE".equals(r.decision())){var before=service.detail(id,null,true,null);if("REFUND".equals(before.get("action"))&&r.refundChannel()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"refundChannel is required");}var outcome=service.review(id,a.getName(),r);if("REFUND".equals(outcome.action())&&"REFUND_PENDING".equals(outcome.status()))refunds.createForCase(id,outcome.shippingRefundFen(),r.refundChannel(),a.getName());return service.detail(id,null,true,null);}
    @GetMapping("/api/supplier/after-sales") public List<Map<String,Object>> supplierCases(Authentication a){return service.supplierList(supplier(a));}
    @GetMapping("/api/supplier/after-sales/{id}") public Map<String,Object> supplierDetail(Authentication a,@PathVariable long id){return service.detail(id,null,false,supplier(a));}
    @PostMapping("/api/customer/after-sales/{id}/evidence") public Map<String,Object> upload(Authentication a,@PathVariable long id,@RequestParam("file") MultipartFile file) throws Exception {long owner=customer(a);service.detail(id,owner,false,null);if(file.isEmpty()||file.getSize()>5*1024*1024)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Evidence must be 1 byte to 5 MB");String type=Objects.toString(file.getContentType(),"");if(!Set.of("image/jpeg","image/png","image/webp").contains(type))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only JPEG, PNG or WebP evidence is allowed");String key="private/after-sales/"+id+"/"+UUID.randomUUID();storage.put(key,file.getInputStream(),file.getSize(),type);var kh=new GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement("INSERT INTO after_sale_evidence(case_id,uploader_consumer_id,object_key,content_type,size_bytes) VALUES (?,?,?,?,?)",new String[]{"id"});p.setLong(1,id);p.setLong(2,owner);p.setString(3,key);p.setString(4,type);p.setLong(5,file.getSize());return p;},kh);return Map.of("id",kh.getKey().longValue(),"contentType",type,"sizeBytes",file.getSize());}
    @GetMapping("/api/customer/after-sales/evidence/{id}") public ResponseEntity<InputStreamResource> customerEvidence(Authentication a,@PathVariable long id)throws Exception{return evidence(id,"customer",customer(a));}
    @GetMapping("/api/admin/after-sales/evidence/{id}") public ResponseEntity<InputStreamResource> adminEvidence(@PathVariable long id)throws Exception{return evidence(id,"admin",0);}
    @GetMapping("/api/supplier/after-sales/evidence/{id}") public ResponseEntity<InputStreamResource> supplierEvidence(Authentication a,@PathVariable long id)throws Exception{return evidence(id,"supplier",supplier(a));}
    private ResponseEntity<InputStreamResource> evidence(long id,String role,long owner)throws Exception{String scope=switch(role){case"customer"->" AND c.consumer_id=?";case"supplier"->" AND EXISTS(SELECT 1 FROM after_sale_item ai JOIN order_item oi ON oi.id=ai.order_item_id WHERE ai.case_id=c.id AND oi.supplier_id=?)";default->"";};Object[] args="admin".equals(role)?new Object[]{id}:new Object[]{id,owner};var rows=db.query("SELECT e.object_key,e.content_type FROM after_sale_evidence e JOIN after_sale_case c ON c.id=e.case_id WHERE e.id=?"+scope,(rs,n)->new String[]{rs.getString(1),rs.getString(2)},args);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var object=storage.get(rows.getFirst()[0]);return ResponseEntity.ok().contentType(MediaType.parseMediaType(rows.getFirst()[1])).header(HttpHeaders.CACHE_CONTROL,"private, no-store").body(new InputStreamResource(object.stream()));}
    record SimulateRefund(@NotBlank @Pattern(regexp="SUCCESS|FAILED|UNKNOWN") String result,String eventKey,@Min(0) @Max(30000) Long delayMs){}
    @PostMapping("/api/admin/refund-attempts/{attemptNo}/simulate") public Map<String,Object> simulate(@PathVariable String attemptNo,@Valid @RequestBody SimulateRefund r)throws Exception{var rows=db.query("SELECT a.channel,a.channel_refund_no,o.channel_request_no,o.amount_fen,o.currency FROM refund_attempt a JOIN refund_order o ON o.id=a.refund_order_id WHERE a.attempt_no=?",(rs,n)->new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getLong(4),rs.getString(5)},attemptNo);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var x=rows.getFirst();if(!"DEV_SIMULATOR".equals(x[0]))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Only development refunds can be simulated");String key=r.eventKey()==null?"DEV-RF-EVT-"+UUID.randomUUID():r.eventKey();var notice=new RefundAdapter.RefundNotice(key,(String)x[2],r.result(),(String)x[1],(long)x[3],(String)x[4]);String payload=json.writeValueAsString(notice);var adapter=refundAdapters.require("DEV_SIMULATOR");long delay=r.delayMs()==null?0:r.delayMs();if(delay>0){CompletableFuture.delayedExecutor(delay,TimeUnit.MILLISECONDS).execute(()->refunds.processNotice("DEV_SIMULATOR",adapter.verifyAndParse(payload,"dev-internal")));return Map.of("status","SCHEDULED","eventKey",key);}var result=refunds.processNotice("DEV_SIMULATOR",adapter.verifyAndParse(payload,"dev-internal"));return Map.of("status",result.status(),"duplicate",result.duplicate(),"detail",result.detail(),"eventKey",key);}
    @GetMapping("/api/admin/refunds") public List<Map<String,Object>> refundList(){return refunds.adminList();}
    record AnomalyRefund(@Positive long amountFen,@NotBlank @Pattern(regexp="DEV_SIMULATOR|WECHAT|ALIPAY") String channel,@NotBlank @Size(max=240) String reason){}
    @PostMapping("/api/admin/payment-anomalies/{id}/refunds") public RefundService.RefundView anomalyRefund(Authentication a,@PathVariable long id,@Valid @RequestBody AnomalyRefund r){return refunds.createForAnomaly(id,r.amountFen(),r.channel(),a.getName(),r.reason());}
}
