package com.orchard.mall;

import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@Service
public class FulfillmentService {
    private final JdbcTemplate db;public FulfillmentService(JdbcTemplate db){this.db=db;}
    public record ParcelLine(@Positive long taskItemId,@Positive int quantity){}
    public record ParcelRequest(@NotBlank @Pattern(regexp="[A-Za-z0-9_-]{8,100}") String idempotencyKey,
        @NotBlank @Size(max=40) String carrierCode,@NotBlank @Size(max=80) String carrierName,
        @NotBlank @Size(max=100) String trackingNo,@NotEmpty @Size(max=100) List<ParcelLine> items){}
    private long insert(String sql,Object... args){var k=new GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement(sql,new String[]{"id"});for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},k);return k.getKey().longValue();}
    public long supplierId(String principal){return Long.parseLong(principal.split(":")[1]);}
    public List<Map<String,Object>> list(Long supplier){String where=supplier==null?"":" WHERE t.supplier_id=?";Object[] args=supplier==null?new Object[]{}:new Object[]{supplier};return db.query("SELECT t.id,t.task_no,o.order_no,t.supplier_id,s.name,t.status,t.task_type,t.created_at FROM fulfillment_task t JOIN sales_order o ON o.id=t.sales_order_id JOIN supplier s ON s.id=t.supplier_id"+where+" ORDER BY t.id DESC",(rs,n)->Map.of("id",rs.getLong(1),"taskNo",rs.getString(2),"orderNo",rs.getString(3),"supplierId",rs.getLong(4),"supplierName",rs.getString(5),"status",rs.getString(6),"taskType",rs.getString(7),"createdAt",rs.getTimestamp(8).toLocalDateTime().toString()),args);}
    public Map<String,Object> detail(long taskId,Long supplier){
        String owner=supplier==null?"":" AND t.supplier_id=?";Object[] args=supplier==null?new Object[]{taskId}:new Object[]{taskId,supplier};
        var tasks=db.query("SELECT t.id,t.task_no,t.status,t.supplier_id,o.order_no,o.recipient,o.mobile,o.province_name,o.city_name,o.district_name,o.address_detail,t.task_type FROM fulfillment_task t JOIN sales_order o ON o.id=t.sales_order_id WHERE t.id=?"+owner,(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getLong(1));m.put("taskNo",rs.getString(2));m.put("status",rs.getString(3));m.put("supplierId",rs.getLong(4));m.put("orderNo",rs.getString(5));m.put("recipient",rs.getString(6));m.put("mobile",rs.getString(7));m.put("address",rs.getString(8)+rs.getString(9)+rs.getString(10)+rs.getString(11));m.put("taskType",rs.getString(12));return m;},args);
        if(tasks.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        var result=tasks.getFirst();result.put("items",db.query("SELECT id,product_title,sku_code,spec_json,required_qty,shipped_qty,frozen_qty,cancelled_qty FROM fulfillment_task_item WHERE task_id=? ORDER BY id",(rs,n)->Map.of("id",rs.getLong(1),"productTitle",rs.getString(2),"skuCode",rs.getString(3),"specJson",rs.getString(4),"requiredQty",rs.getInt(5),"shippedQty",rs.getInt(6),"frozenQty",rs.getInt(7),"cancelledQty",rs.getInt(8)),taskId));
        result.put("parcels",parcels(taskId));return result;
    }
    public List<Map<String,Object>> parcels(long taskId){return db.query("SELECT id,carrier_code,carrier_name,tracking_no,created_by_type,created_by,created_at,received_at FROM parcel WHERE task_id=? ORDER BY id",(rs,n)->{var m=new LinkedHashMap<String,Object>();long id=rs.getLong(1);m.put("id",id);m.put("carrierCode",rs.getString(2));m.put("carrierName",rs.getString(3));m.put("trackingNo",rs.getString(4));m.put("createdByType",rs.getString(5));m.put("createdBy",rs.getString(6));m.put("createdAt",rs.getTimestamp(7).toLocalDateTime().toString());m.put("receivedAt",rs.getTimestamp(8)==null?null:rs.getTimestamp(8).toLocalDateTime().toString());m.put("items",db.query("SELECT i.task_item_id,t.product_title,t.sku_code,i.quantity FROM parcel_item i JOIN fulfillment_task_item t ON t.id=i.task_item_id WHERE i.parcel_id=?",(x,j)->Map.of("taskItemId",x.getLong(1),"productTitle",x.getString(2),"skuCode",x.getString(3),"quantity",x.getInt(4)),id));return m;},taskId);}
    @Transactional public void accept(long taskId,long supplier,String actor){int n=db.update("UPDATE fulfillment_task SET status='ACCEPTED',accepted_at=CURRENT_TIMESTAMP,accepted_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND supplier_id=? AND status='PENDING_ACCEPTANCE'",actor,taskId,supplier);if(n==0){var found=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE id=? AND supplier_id=?",Integer.class,taskId,supplier);if(found==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND);}}
    @Transactional public Map<String,Object> createParcel(long taskId,Long supplier,String actorType,String actor,ParcelRequest r){
        String lookup="SELECT sales_order_id FROM fulfillment_task WHERE id=?"+(supplier==null?"":" AND supplier_id=?");Object[] lookupArgs=supplier==null?new Object[]{taskId}:new Object[]{taskId,supplier};var orderIds=db.query(lookup,(rs,n)->rs.getLong(1),lookupArgs);if(orderIds.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);db.queryForList("SELECT id FROM sales_order WHERE id=? FOR UPDATE",orderIds.getFirst());
        String lock="SELECT status,sales_order_id,task_type FROM fulfillment_task WHERE id=?"+(supplier==null?"":" AND supplier_id=?")+" FOR UPDATE";Object[] args=supplier==null?new Object[]{taskId}:new Object[]{taskId,supplier};var task=db.query(lock,(rs,n)->new Object[]{rs.getString(1),rs.getLong(2),rs.getString(3)},args);if(task.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        var existing=db.query("SELECT id FROM parcel WHERE task_id=? AND idempotency_key=?",(rs,n)->rs.getLong(1),taskId,r.idempotencyKey());if(!existing.isEmpty())return parcels(taskId).stream().filter(p->Objects.equals(p.get("id"),existing.getFirst())).findFirst().orElseThrow();
        if("PENDING_ACCEPTANCE".equals(task.getFirst()[0])) {
            if(supplier!=null) throw new ResponseStatusException(HttpStatus.CONFLICT,"Task must be accepted first");
            db.update("UPDATE fulfillment_task SET status='ACCEPTED',accepted_at=CURRENT_TIMESTAMP,accepted_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",actor,taskId);
        }
        var requested=new HashMap<Long,Integer>();for(var line:r.items())requested.merge(line.taskItemId(),line.quantity(),Math::addExact);
        var items=db.query("SELECT id,required_qty,shipped_qty,frozen_qty,cancelled_qty FROM fulfillment_task_item WHERE task_id=? ORDER BY id FOR UPDATE",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2),rs.getLong(3),rs.getLong(4),rs.getLong(5)},taskId);
        for(var i:items){int q=requested.getOrDefault(i[0],0);if(q>0&&i[2]+i[3]+i[4]+q>i[1])throw new ResponseStatusException(HttpStatus.CONFLICT,"Shipment quantity exceeds unfrozen effective quantity");requested.remove(i[0]);}
        if(!requested.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Parcel item does not belong to task");
        long parcelId=insert("INSERT INTO parcel(task_id,idempotency_key,carrier_code,carrier_name,tracking_no,created_by_type,created_by) VALUES (?,?,?,?,?,?,?)",taskId,r.idempotencyKey(),r.carrierCode(),r.carrierName(),r.trackingNo(),actorType,actor);
        for(var line:r.items()){db.update("INSERT INTO parcel_item(parcel_id,task_item_id,quantity) VALUES (?,?,?)",parcelId,line.taskItemId(),line.quantity());db.update("UPDATE fulfillment_task_item SET shipped_qty=shipped_qty+? WHERE id=?",line.quantity(),line.taskItemId());}
        if("REPLACEMENT".equals(task.getFirst()[2])){var rr=db.query("SELECT id,supply_id,quantity,consumed_qty FROM replacement_reservation WHERE fulfillment_task_id=? FOR UPDATE",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2),rs.getLong(3),rs.getLong(4)},taskId);if(rr.isEmpty())throw new IllegalStateException("Replacement reservation missing");int sent=r.items().stream().mapToInt(ParcelLine::quantity).sum();var x=rr.getFirst();if(x[3]+sent>x[2])throw new ResponseStatusException(HttpStatus.CONFLICT,"Replacement inventory exceeded");if(db.update("UPDATE supply_inventory SET on_hand_qty=on_hand_qty-?,reserved_qty=reserved_qty-? WHERE supply_id=? AND on_hand_qty>=? AND reserved_qty>=?",sent,sent,x[1],sent,sent)!=1)throw new IllegalStateException("Replacement inventory invariant violated");db.update("UPDATE replacement_reservation SET status=CASE WHEN consumed_qty+?=quantity THEN 'CONSUMED' ELSE 'PARTIAL' END,consumed_qty=consumed_qty+? WHERE id=?",sent,sent,x[0]);db.update("INSERT INTO inventory_movement(supply_id,order_id,delta_on_hand,delta_reserved,reason,actor) VALUES (?,?,?,?, '补发库存消耗',?)",x[1],task.getFirst()[1],-sent,-sent,actor);}
        db.update("INSERT INTO parcel_operation_log(parcel_id,operation,after_value,actor_type,actor) VALUES (?,'CREATE',?,?,?)",parcelId,r.carrierName()+"|"+r.trackingNo(),actorType,actor);
        int remaining=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item WHERE task_id=? AND shipped_qty+cancelled_qty<required_qty",Integer.class,taskId);String status=remaining==0?"SHIPPED":"PARTIALLY_SHIPPED";
        db.update("UPDATE fulfillment_task SET status=?,shipped_at=CASE WHEN ?='SHIPPED' THEN CURRENT_TIMESTAMP ELSE shipped_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?",status,status,taskId);
        long orderId=(long)task.getFirst()[1];if("ORIGINAL".equals(task.getFirst()[2])){int open=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=? AND task_type='ORIGINAL' AND status<>'SHIPPED'",Integer.class,orderId);db.update("UPDATE sales_order SET fulfillment_status=? WHERE id=?",open==0?"SHIPPED":"PARTIALLY_SHIPPED",orderId);}
        return parcels(taskId).stream().filter(p->Objects.equals(p.get("id"),parcelId)).findFirst().orElseThrow();
    }
    @Transactional public void updateParcel(long parcelId,Long supplier,String actorType,String actor,String carrierCode,String carrierName,String trackingNo){
        String sql="SELECT p.carrier_code,p.carrier_name,p.tracking_no FROM parcel p JOIN fulfillment_task t ON t.id=p.task_id WHERE p.id=?"+(supplier==null?"":" AND t.supplier_id=?")+" FOR UPDATE";Object[] args=supplier==null?new Object[]{parcelId}:new Object[]{parcelId,supplier};var old=db.query(sql,(rs,n)->new String[]{rs.getString(1),rs.getString(2),rs.getString(3)},args);if(old.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);db.update("UPDATE parcel SET carrier_code=?,carrier_name=?,tracking_no=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",carrierCode,carrierName,trackingNo,parcelId);db.update("INSERT INTO parcel_operation_log(parcel_id,operation,before_value,after_value,actor_type,actor) VALUES (?,'UPDATE',?,?,?,?)",parcelId,String.join("|",old.getFirst()),carrierName+"|"+trackingNo,actorType,actor);
    }
    @Transactional public Map<String,Object> confirmReceived(long parcelId,long consumer){
        var p=db.query("SELECT p.task_id,p.received_at,t.sales_order_id,t.task_type FROM parcel p JOIN fulfillment_task t ON t.id=p.task_id JOIN sales_order o ON o.id=t.sales_order_id WHERE p.id=? AND o.consumer_id=? FOR UPDATE",(rs,n)->new Object[]{rs.getLong(1),rs.getTimestamp(2),rs.getLong(3),rs.getString(4)},parcelId,consumer);if(p.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var x=p.getFirst();long taskId=(long)x[0];if(x[1]!=null)return parcels(taskId).stream().filter(v->Objects.equals(v.get("id"),parcelId)).findFirst().orElseThrow();db.update("UPDATE parcel SET received_at=CURRENT_TIMESTAMP,received_by_consumer_id=? WHERE id=? AND received_at IS NULL",consumer,parcelId);long orderId=(long)x[2];
        if("ORIGINAL".equals(x[3])){var orderItems=db.query("SELECT DISTINCT ti.order_item_id,t.order_group_id FROM parcel_item pi JOIN fulfillment_task_item ti ON ti.id=pi.task_item_id JOIN fulfillment_task t ON t.id=ti.task_id WHERE pi.parcel_id=?",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2)},parcelId);for(var oi:orderItems)releaseOriginalLedger(oi[0],oi[1]);int incomplete=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item ti JOIN fulfillment_task t ON t.id=ti.task_id WHERE t.sales_order_id=? AND t.task_type='ORIGINAL' AND ((SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel pp ON pp.id=pi.parcel_id WHERE pi.task_item_id=ti.id AND pp.received_at IS NOT NULL)<ti.required_qty-ti.cancelled_qty)",Integer.class,orderId);if(incomplete==0)db.update("UPDATE sales_order SET completion_status='COMPLETED',completed_at=CURRENT_TIMESTAMP WHERE id=? AND completion_status='NOT_COMPLETED'",orderId);
        }else{int pending=db.queryForObject("SELECT COUNT(*) FROM parcel WHERE task_id=? AND received_at IS NULL",Integer.class,taskId);if(pending==0){var cases=db.query("SELECT after_sale_case_id FROM replacement_reservation WHERE fulfillment_task_id=?",(rs,n)->rs.getLong(1),taskId);if(!cases.isEmpty()){long caseId=cases.getFirst();db.update("UPDATE after_sale_case SET status='COMPLETED',completed_at=CURRENT_TIMESTAMP WHERE id=? AND status='REPLACEMENT_PENDING'",caseId);db.update("INSERT INTO after_sale_operation(case_id,operation,detail,actor_type,actor) VALUES (?,'REPLACEMENT_RECEIVED',?,'CUSTOMER',?)",caseId,"parcel="+parcelId,"consumer:"+consumer);var original=db.query("SELECT ai.order_item_id,oi.group_id FROM after_sale_item ai JOIN order_item oi ON oi.id=ai.order_item_id WHERE ai.case_id=?",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2)},caseId);for(var oi:original)releaseOriginalLedger(oi[0],oi[1]);int open=db.queryForObject("SELECT COUNT(*) FROM after_sale_case WHERE sales_order_id=? AND status NOT IN ('REJECTED','CANCELLED','COMPLETED')",Integer.class,orderId);if(open==0)db.update("UPDATE sales_order SET after_sales_status='CLOSED' WHERE id=?",orderId);}}}
        return parcels(taskId).stream().filter(v->Objects.equals(v.get("id"),parcelId)).findFirst().orElseThrow();
    }
    private void releaseOriginalLedger(long item,long group){int effective=db.queryForObject("SELECT required_qty-cancelled_qty FROM fulfillment_task_item ti JOIN fulfillment_task t ON t.id=ti.task_id WHERE ti.order_item_id=? AND t.task_type='ORIGINAL'",Integer.class,item);int confirmed=db.queryForObject("SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel p ON p.id=pi.parcel_id JOIN fulfillment_task_item ti ON ti.id=pi.task_item_id JOIN fulfillment_task t ON t.id=ti.task_id WHERE ti.order_item_id=? AND t.task_type='ORIGINAL' AND p.received_at IS NOT NULL",Integer.class,item);int pending=db.queryForObject("SELECT COUNT(*) FROM after_sale_item ai JOIN after_sale_case c ON c.id=ai.case_id WHERE ai.order_item_id=? AND c.status NOT IN ('REJECTED','CANCELLED','COMPLETED')",Integer.class,item);if(confirmed>=effective&&pending==0)db.update("UPDATE supplier_ledger_entry SET status='AVAILABLE',available_at=CURRENT_TIMESTAMP WHERE source_key=? AND status='FROZEN'","goods:"+item);int groupPending=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item ti JOIN order_item oi ON oi.id=ti.order_item_id WHERE oi.group_id=? AND (SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel pp ON pp.id=pi.parcel_id WHERE pi.task_item_id=ti.id AND pp.received_at IS NOT NULL)<ti.required_qty-ti.cancelled_qty",Integer.class,group);if(groupPending==0)db.update("UPDATE supplier_ledger_entry SET status='AVAILABLE',available_at=CURRENT_TIMESTAMP WHERE source_key=? AND status='FROZEN'","shipping:"+group);}
}
