package com.orchard.mall;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

@Service
public class RefundService {
    private final JdbcTemplate db;private final RefundAdapters adapters;private final TransactionTemplate tx;private final ObjectMapper json;private final RefundProcessingFaultInjector faults;
    public RefundService(JdbcTemplate db,RefundAdapters adapters,PlatformTransactionManager manager,ObjectMapper json,RefundProcessingFaultInjector faults){this.db=db;this.adapters=adapters;this.tx=new TransactionTemplate(manager);this.json=json;this.faults=faults;}
    public record RefundView(long id,String refundNo,String channelRequestNo,String status,long amountFen,String currency,String attemptNo,String channel){}
    public record Result(String status,boolean duplicate,String detail){}
    private record Prepared(RefundView view,String channelTransactionNo,String reason,boolean call){}
    private long insert(String sql,Object... args){var k=new GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement(sql,new String[]{"id"});for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},k);return k.getKey().longValue();}
    public RefundView createForCase(long caseId,long shippingRefundFen,String channel,String actor){
        Prepared p=tx.execute(s->{
            var c=db.query("SELECT c.status,c.approved_refund_fen,c.sales_order_id,c.reason_code FROM after_sale_case c WHERE c.id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getLong(2),rs.getLong(3),rs.getString(4)},caseId);if(c.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);if(!List.of("REFUND_PENDING","REFUND_FAILED").contains(c.getFirst()[0]))throw new ResponseStatusException(HttpStatus.CONFLICT,"Case is not ready for refund");
            long orderId=(long)c.getFirst()[2];db.queryForList("SELECT id FROM sales_order WHERE id=? FOR UPDATE",orderId);
            var pay=db.query("SELECT p.id,p.amount_fen,p.currency,a.channel,a.channel_transaction_no FROM payment_order p JOIN payment_attempt a ON a.payment_order_id=p.id AND a.status='SUCCEEDED' WHERE p.sales_order_id=? ORDER BY a.id LIMIT 1 FOR UPDATE",(rs,n)->new Object[]{rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getString(4),rs.getString(5)},orderId);if(pay.isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"No successful payment transaction");var x=pay.getFirst();
            var existing=db.query("SELECT r.id,r.refund_no,r.channel_request_no,r.status,r.amount_fen,r.currency,a.attempt_no,a.channel,a.status FROM refund_order r JOIN refund_attempt a ON a.refund_order_id=r.id WHERE r.after_sale_case_id=? ORDER BY a.id DESC LIMIT 1",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getLong(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)},caseId);
            if(!existing.isEmpty()){var e=existing.getFirst();var view=new RefundView((long)e[0],(String)e[1],(String)e[2],(String)e[3],(long)e[4],(String)e[5],(String)e[6],(String)e[7]);if(List.of("PENDING","UNKNOWN","SUCCEEDED").contains(e[8]))return new Prepared(view,(String)x[4],(String)c.getFirst()[3],false);String attempt="RFA"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);insert("INSERT INTO refund_attempt(refund_order_id,attempt_no,channel,status) VALUES (?,?,?,'CREATED')",e[0],attempt,channel);return new Prepared(new RefundView((long)e[0],(String)e[1],(String)e[2],"CREATED",(long)e[4],(String)e[5],attempt,channel),(String)x[4],(String)c.getFirst()[3],true);}
            long amount=(long)c.getFirst()[1];long occupied=db.queryForObject("SELECT COALESCE(SUM(amount_fen),0) FROM refund_order WHERE payment_order_id=? AND status IN ('PENDING','UNKNOWN','SUCCEEDED')",Long.class,x[0]);if(Math.addExact(occupied,amount)>(long)x[1])throw new ResponseStatusException(HttpStatus.CONFLICT,"Refunds exceed collected payment");
            long lineOccupied=db.queryForObject("SELECT COALESCE(SUM(r.amount_fen-r.shipping_amount_fen),0) FROM refund_order r JOIN after_sale_case c2 ON c2.id=r.after_sale_case_id JOIN after_sale_item ai2 ON ai2.case_id=c2.id WHERE c2.sales_order_id=? AND r.status IN ('PENDING','UNKNOWN','SUCCEEDED')",Long.class,orderId);long orderItems=db.queryForObject("SELECT item_amount_fen FROM sales_order WHERE id=?",Long.class,orderId);if(lineOccupied+amount-shippingRefundFen>orderItems)throw new ResponseStatusException(HttpStatus.CONFLICT,"Refunds exceed order item paid amount");
            String refundNo="RF"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT),requestNo="RFR"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);long id=insert("INSERT INTO refund_order(refund_no,channel_request_no,payment_order_id,after_sale_case_id,amount_fen,shipping_amount_fen,currency,status,reason,created_by) VALUES (?,?,?,?,?,?,?,'CREATED',?,?)",refundNo,requestNo,x[0],caseId,amount,shippingRefundFen,x[2],c.getFirst()[3],actor);String attempt="RFA"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);insert("INSERT INTO refund_attempt(refund_order_id,attempt_no,channel,status) VALUES (?,?,?,'CREATED')",id,attempt,channel);return new Prepared(new RefundView(id,refundNo,requestNo,"CREATED",amount,(String)x[2],attempt,channel),(String)x[4],(String)c.getFirst()[3],true);
        });
        return invoke(p);
    }
    public RefundView createForAnomaly(long anomalyId,long amount,String channel,String actor,String reason){
        Prepared p=tx.execute(s->{var a=db.query("SELECT a.payment_order_id,a.amount_fen,a.status,p.currency,pa.channel,pa.channel_transaction_no FROM payment_anomaly a JOIN payment_order p ON p.id=a.payment_order_id JOIN payment_attempt pa ON pa.id=a.payment_attempt_id WHERE a.id=? FOR UPDATE",(rs,n)->new Object[]{rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)},anomalyId);if(a.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var x=a.getFirst();long used=db.queryForObject("SELECT COALESCE(SUM(amount_fen),0) FROM refund_order WHERE payment_anomaly_id=? AND status IN ('PENDING','UNKNOWN','SUCCEEDED')",Long.class,anomalyId);if(amount<=0||used+amount>(long)x[1])throw new ResponseStatusException(HttpStatus.CONFLICT,"Refund exceeds anomalous collection balance");String refundNo="RF"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT),requestNo="RFR"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);long id=insert("INSERT INTO refund_order(refund_no,channel_request_no,payment_order_id,payment_anomaly_id,amount_fen,currency,status,reason,created_by) VALUES (?,?,?,?,?,?,'CREATED',?,?)",refundNo,requestNo,x[0],anomalyId,amount,x[3],reason,actor);String attempt="RFA"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);insert("INSERT INTO refund_attempt(refund_order_id,attempt_no,channel,status) VALUES (?,?,?,'CREATED')",id,attempt,channel);return new Prepared(new RefundView(id,refundNo,requestNo,"CREATED",amount,(String)x[3],attempt,channel),(String)x[5],reason,true);});return invoke(p);
    }
    private RefundView invoke(Prepared p){if(!p.call())return p.view();var v=p.view();RefundAdapter.CreateResult result;try{result=adapters.require(v.channel()).create(new RefundAdapter.CreateCommand(v.refundNo(),v.channelRequestNo(),p.channelTransactionNo(),v.amountFen(),v.currency(),p.reason()));}catch(RuntimeException e){tx.executeWithoutResult(s->{db.update("UPDATE refund_attempt SET status='UNKNOWN',failure_code='CREATE_UNCERTAIN' WHERE attempt_no=?",v.attemptNo());db.update("UPDATE refund_order SET status='UNKNOWN',updated_at=CURRENT_TIMESTAMP WHERE id=?",v.id());});throw e;}tx.executeWithoutResult(s->{db.update("UPDATE refund_attempt SET status=?,channel_refund_no=?,updated_at=CURRENT_TIMESTAMP WHERE attempt_no=?",result.status(),result.channelRefundNo(),v.attemptNo());db.update("UPDATE refund_order SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",result.status(),v.id());});return new RefundView(v.id(),v.refundNo(),v.channelRequestNo(),result.status(),v.amountFen(),v.currency(),v.attemptNo(),v.channel());}
    public Result processNotice(String channel,RefundAdapter.RefundNotice n){long event=receive(channel,n);try{return tx.execute(s->process(event,channel,n));}catch(RuntimeException e){recordFailure(event,e);throw e;}}
    private long receive(String channel,RefundAdapter.RefundNotice n){String payload;try{payload=json.writeValueAsString(n);}catch(Exception e){throw new IllegalArgumentException(e);}String hash=SecurityConfig.digest(payload);try{return tx.execute(s->{var old=db.query("SELECT id,payload_hash FROM refund_event WHERE channel=? AND event_key=?",(rs,x)->new Object[]{rs.getLong(1),rs.getString(2)},channel,n.eventKey());if(!old.isEmpty()){if(!hash.equals(old.getFirst()[1]))throw new ResponseStatusException(HttpStatus.CONFLICT,"Refund event key payload mismatch");return (long)old.getFirst()[0];}var a=db.query("SELECT a.id,a.refund_order_id FROM refund_attempt a JOIN refund_order r ON r.id=a.refund_order_id WHERE r.channel_request_no=? AND a.channel=? ORDER BY a.id DESC LIMIT 1",(rs,x)->new long[]{rs.getLong(1),rs.getLong(2)},n.channelRequestNo(),channel);if(a.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);return insert("INSERT INTO refund_event(refund_order_id,refund_attempt_id,channel,event_key,payload_hash,payload_json,processing_status) VALUES (?,?,?,?,?,?,'RECEIVED')",a.getFirst()[1],a.getFirst()[0],channel,n.eventKey(),hash,payload);});}catch(DataIntegrityViolationException e){return db.queryForObject("SELECT id FROM refund_event WHERE channel=? AND event_key=?",Long.class,channel,n.eventKey());}}
    private Result process(long event,String channel,RefundAdapter.RefundNotice n){var ev=db.query("SELECT processing_status FROM refund_event WHERE id=? FOR UPDATE",(rs,x)->rs.getString(1),event);if(ev.isEmpty())throw new IllegalStateException("Refund event missing");if("PROCESSED".equals(ev.getFirst()))return new Result("DUPLICATE",true,"Already processed");db.update("UPDATE refund_event SET processing_status='PROCESSING',attempt_count=attempt_count+1,failure_reason=NULL WHERE id=?",event);
        var r=db.query("SELECT r.id,r.payment_order_id,r.payment_anomaly_id,r.after_sale_case_id,r.amount_fen,r.currency,r.status,a.id FROM refund_order r JOIN refund_attempt a ON a.refund_order_id=r.id WHERE r.channel_request_no=? AND a.channel=? ORDER BY a.id DESC LIMIT 1 FOR UPDATE",(rs,x)->new Object[]{rs.getLong(1),rs.getLong(2),rs.getObject(3),rs.getObject(4),rs.getLong(5),rs.getString(6),rs.getString(7),rs.getLong(8)},n.channelRequestNo(),channel);if(r.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var x=r.getFirst();if((long)x[4]!=n.amountFen()||!Objects.equals(x[5],n.currency())){db.update("UPDATE refund_event SET processing_status='REJECTED',failure_reason='AMOUNT_OR_CURRENCY_MISMATCH',processed_at=CURRENT_TIMESTAMP WHERE id=?",event);return new Result("REJECTED",false,"Amount or currency mismatch");}
        if("UNKNOWN".equals(n.status())){db.update("UPDATE refund_order SET status='UNKNOWN',updated_at=CURRENT_TIMESTAMP WHERE id=?",x[0]);db.update("UPDATE refund_attempt SET status='UNKNOWN',channel_refund_no=COALESCE(channel_refund_no,?) WHERE id=?",n.channelRefundNo(),x[7]);complete(event);return new Result("UNKNOWN",false,"Refund result unknown");}
        if("FAILED".equals(n.status())){db.update("UPDATE refund_order SET status='FAILED',updated_at=CURRENT_TIMESTAMP WHERE id=?",x[0]);db.update("UPDATE refund_attempt SET status='FAILED',channel_refund_no=COALESCE(channel_refund_no,?) WHERE id=?",n.channelRefundNo(),x[7]);if(x[3]!=null)db.update("UPDATE after_sale_case SET status='REFUND_FAILED' WHERE id=?",x[3]);complete(event);return new Result("FAILED",false,"Refund failed");}
        if(!"SUCCESS".equals(n.status()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unsupported refund status");
        db.update("INSERT INTO refund_ledger(refund_order_id,payment_order_id,payment_anomaly_id,amount_fen) SELECT ?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM refund_ledger WHERE refund_order_id=?)",x[0],x[1],x[2],x[4],x[0]);db.update("UPDATE refund_order SET status='SUCCEEDED',completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",x[0]);db.update("UPDATE refund_attempt SET status='SUCCEEDED',channel_refund_no=? WHERE id=?",n.channelRefundNo(),x[7]);if(x[3]!=null){db.update("UPDATE after_sale_case SET status='COMPLETED',completed_at=CURRENT_TIMESTAMP WHERE id=?",x[3]);db.update("INSERT INTO after_sale_operation(case_id,operation,detail,actor_type,actor) VALUES (?,'REFUND_SUCCEEDED',?,'SYSTEM','refund-event')",x[3],"refundOrder="+x[0]);releaseReceivedLedger((long)x[3]);Long orderId=db.queryForObject("SELECT sales_order_id FROM after_sale_case WHERE id=?",Long.class,x[3]);int open=db.queryForObject("SELECT COUNT(*) FROM after_sale_case WHERE sales_order_id=? AND status NOT IN ('REJECTED','CANCELLED','COMPLETED')",Integer.class,orderId);if(open==0)db.update("UPDATE sales_order SET after_sales_status='CLOSED' WHERE id=?",orderId);}if(x[2]!=null)db.update("UPDATE payment_anomaly SET status='RESOLVED' WHERE id=?",x[2]);faults.beforeCommit(n.eventKey());complete(event);return new Result("SUCCESS",false,"Refund completed");}
    private void releaseReceivedLedger(long caseId){var items=db.query("SELECT ai.order_item_id,oi.group_id FROM after_sale_item ai JOIN order_item oi ON oi.id=ai.order_item_id WHERE ai.case_id=?",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2)},caseId);for(var x:items){int effective=db.queryForObject("SELECT required_qty-cancelled_qty FROM fulfillment_task_item ti JOIN fulfillment_task t ON t.id=ti.task_id WHERE ti.order_item_id=? AND t.task_type='ORIGINAL'",Integer.class,x[0]);int received=db.queryForObject("SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel p ON p.id=pi.parcel_id JOIN fulfillment_task_item ti ON ti.id=pi.task_item_id JOIN fulfillment_task t ON t.id=ti.task_id WHERE ti.order_item_id=? AND t.task_type='ORIGINAL' AND p.received_at IS NOT NULL",Integer.class,x[0]);int open=db.queryForObject("SELECT COUNT(*) FROM after_sale_item ai JOIN after_sale_case c ON c.id=ai.case_id WHERE ai.order_item_id=? AND c.status NOT IN ('REJECTED','CANCELLED','COMPLETED')",Integer.class,x[0]);if(received>=effective&&open==0)db.update("UPDATE supplier_ledger_entry SET status='AVAILABLE',available_at=CURRENT_TIMESTAMP WHERE source_key=? AND status='FROZEN'","goods:"+x[0]);int groupOpen=db.queryForObject("SELECT COUNT(*) FROM fulfillment_task_item ti JOIN order_item oi ON oi.id=ti.order_item_id WHERE oi.group_id=? AND (SELECT COALESCE(SUM(pi.quantity),0) FROM parcel_item pi JOIN parcel p ON p.id=pi.parcel_id WHERE pi.task_item_id=ti.id AND p.received_at IS NOT NULL)<ti.required_qty-ti.cancelled_qty",Integer.class,x[1]);if(groupOpen==0)db.update("UPDATE supplier_ledger_entry SET status='AVAILABLE',available_at=CURRENT_TIMESTAMP WHERE source_key=? AND status='FROZEN'","shipping:"+x[1]);}}
    private void complete(long event){db.update("UPDATE refund_event SET processing_status='PROCESSED',processed_at=CURRENT_TIMESTAMP WHERE id=?",event);}
    private void recordFailure(long event,Exception e){String f=e.getClass().getSimpleName()+":"+Objects.toString(e.getMessage(),"");if(f.length()>240)f=f.substring(0,240);db.update("UPDATE refund_event SET processing_status='RECEIVED',failure_reason=?,next_attempt_at=? WHERE id=? AND processing_status<>'PROCESSED'",f,LocalDateTime.now().plusSeconds(10),event);}
    @Scheduled(fixedDelayString="${app.refund-event-recovery-ms:10000}") public void recover(){var events=db.query("SELECT id,channel,payload_json FROM refund_event WHERE processing_status='RECEIVED' AND next_attempt_at<=CURRENT_TIMESTAMP ORDER BY id LIMIT 50",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2),rs.getString(3)});for(var e:events)try{var n=json.readValue((String)e[2],RefundAdapter.RefundNotice.class);tx.execute(s->process((long)e[0],(String)e[1],n));}catch(Exception x){recordFailure((long)e[0],x);}}
    public List<Map<String,Object>> adminList(){return db.query("SELECT r.id,r.refund_no,r.channel_request_no,r.amount_fen,r.currency,r.status,r.reason,r.created_at,c.case_no,a.anomaly_type FROM refund_order r LEFT JOIN after_sale_case c ON c.id=r.after_sale_case_id LEFT JOIN payment_anomaly a ON a.id=r.payment_anomaly_id ORDER BY r.id DESC",(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getLong(1));m.put("refundNo",rs.getString(2));m.put("channelRequestNo",rs.getString(3));m.put("amountFen",rs.getLong(4));m.put("currency",rs.getString(5));m.put("status",rs.getString(6));m.put("reason",rs.getString(7));m.put("createdAt",rs.getTimestamp(8).toLocalDateTime().toString());m.put("caseNo",rs.getString(9));m.put("anomalyType",rs.getString(10));return m;});}
}

/** Package-private deterministic fault seam used only by transaction recovery tests; no HTTP surface. */
@Component
class RefundProcessingFaultInjector {
    private final Set<String> failOnce=ConcurrentHashMap.newKeySet();
    void failNext(String eventKey){failOnce.add(eventKey);}
    void beforeCommit(String eventKey){if(failOnce.remove(eventKey))throw new IllegalStateException("Injected refund transaction failure");}
}
