package com.orchard.mall;

import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDate;
import java.util.*;

@Service
public class SettlementService {
    private final JdbcTemplate db;public SettlementService(JdbcTemplate db){this.db=db;}
    public record StatementRequest(@Positive long supplierId,@NotEmpty List<@Positive Long> ledgerEntryIds){}
    public record PaymentRequest(@NotBlank @Pattern(regexp="[A-Za-z0-9_-]{8,100}") String idempotencyKey,@Positive long amountFen,@NotNull LocalDate paidOn,@NotBlank @Size(max=100) String referenceNo,@Size(max=240) String note){}
    public record AdjustmentRequest(@Positive long supplierId,Long orderId,@NotBlank @Pattern(regexp="OTHER_ADJUSTMENT|AFTER_SALE_DEDUCTION") String type,long amountFen,@NotBlank @Size(max=240) String reason,@NotBlank @Pattern(regexp="[A-Za-z0-9_-]{8,100}") String idempotencyKey){}
    private long insert(String sql,Object... args){var k=new GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement(sql,new String[]{"id"});for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},k);return k.getKey().longValue();}
    public List<Map<String,Object>> ledger(Long supplier){String where=supplier==null?"":" WHERE l.supplier_id=?";Object[] args=supplier==null?new Object[]{}:new Object[]{supplier};return db.query("SELECT l.id,l.supplier_id,s.name,l.sales_order_id,o.order_no,l.entry_type,l.quantity,l.amount_fen,l.status,l.description,l.created_at FROM supplier_ledger_entry l JOIN supplier s ON s.id=l.supplier_id LEFT JOIN sales_order o ON o.id=l.sales_order_id"+where+" ORDER BY l.id DESC",(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getLong(1));m.put("supplierId",rs.getLong(2));m.put("supplierName",rs.getString(3));m.put("orderId",rs.getObject(4));m.put("orderNo",rs.getString(5));m.put("type",rs.getString(6));m.put("quantity",rs.getInt(7));m.put("amountFen",rs.getLong(8));m.put("status",rs.getString(9));m.put("description",rs.getString(10));m.put("createdAt",rs.getTimestamp(11).toLocalDateTime().toString());return m;},args);}
    @Transactional public Map<String,Object> createStatement(StatementRequest r,String actor){var ids=new TreeSet<>(r.ledgerEntryIds());String placeholders=String.join(",",Collections.nCopies(ids.size(),"?"));var args=new ArrayList<Object>();args.addAll(ids);var rows=db.query("SELECT id,amount_fen FROM supplier_ledger_entry WHERE id IN ("+placeholders+") AND supplier_id=? AND status='AVAILABLE' ORDER BY id FOR UPDATE",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2)},append(args,r.supplierId()));if(rows.size()!=ids.size())throw new ResponseStatusException(HttpStatus.CONFLICT,"Ledger entry is unavailable or already in a statement");long total=rows.stream().mapToLong(x->x[1]).sum();if(total<=0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Statement total must be positive");long id=insert("INSERT INTO settlement_statement(statement_no,supplier_id,total_amount_fen,status,created_by) VALUES (?,?,?,'UNPAID',?)","ST"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT),r.supplierId(),total,actor);for(var x:rows){db.update("INSERT INTO settlement_statement_item(statement_id,ledger_entry_id,locked_amount_fen) VALUES (?,?,?)",id,x[0],x[1]);db.update("UPDATE supplier_ledger_entry SET status='IN_STATEMENT' WHERE id=? AND status='AVAILABLE'",x[0]);}return statement(id,null,true);}
    private Object[] append(List<Object> values,Object tail){values.add(tail);return values.toArray();}
    public List<Map<String,Object>> statements(Long supplier){String where=supplier==null?"":" WHERE st.supplier_id=?";Object[] args=supplier==null?new Object[]{}:new Object[]{supplier};return db.query("SELECT st.id,st.statement_no,st.supplier_id,s.name,st.total_amount_fen,st.paid_amount_fen,st.status,st.created_at FROM settlement_statement st JOIN supplier s ON s.id=st.supplier_id"+where+" ORDER BY st.id DESC",(rs,n)->Map.of("id",rs.getLong(1),"statementNo",rs.getString(2),"supplierId",rs.getLong(3),"supplierName",rs.getString(4),"totalAmountFen",rs.getLong(5),"paidAmountFen",rs.getLong(6),"status",rs.getString(7),"createdAt",rs.getTimestamp(8).toLocalDateTime().toString()),args);}
    public Map<String,Object> statement(long id,Long supplier,boolean admin){String scope=admin?"":" AND supplier_id=?";Object[] args=admin?new Object[]{id}:new Object[]{id,supplier};var rows=db.query("SELECT id,statement_no,supplier_id,total_amount_fen,paid_amount_fen,status,created_at FROM settlement_statement WHERE id=?"+scope,(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getLong(1));m.put("statementNo",rs.getString(2));m.put("supplierId",rs.getLong(3));m.put("totalAmountFen",rs.getLong(4));m.put("paidAmountFen",rs.getLong(5));m.put("status",rs.getString(6));m.put("createdAt",rs.getTimestamp(7).toLocalDateTime().toString());return m;},args);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var result=rows.getFirst();result.put("items",db.query("SELECT i.ledger_entry_id,i.locked_amount_fen,l.entry_type,l.description FROM settlement_statement_item i JOIN supplier_ledger_entry l ON l.id=i.ledger_entry_id WHERE i.statement_id=? ORDER BY i.id",(rs,n)->Map.of("ledgerEntryId",rs.getLong(1),"amountFen",rs.getLong(2),"type",rs.getString(3),"description",rs.getString(4)),id));result.put("payments",db.query("SELECT id,amount_fen,paid_on,reference_no,operation,reverses_payment_id,note,actor,created_at FROM settlement_payment_record WHERE statement_id=? ORDER BY id",(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getLong(1));m.put("amountFen",rs.getLong(2));m.put("paidOn",rs.getDate(3).toLocalDate().toString());m.put("referenceNo",rs.getString(4));m.put("operation",rs.getString(5));m.put("reversesPaymentId",rs.getObject(6));m.put("note",rs.getString(7));m.put("actor",rs.getString(8));m.put("createdAt",rs.getTimestamp(9).toLocalDateTime().toString());return m;},id));return result;}
    @Transactional public Map<String,Object> recordPayment(long statementId,PaymentRequest r,String actor){var st=db.query("SELECT total_amount_fen,paid_amount_fen FROM settlement_statement WHERE id=? FOR UPDATE",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2)},statementId);if(st.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var old=db.query("SELECT id FROM settlement_payment_record WHERE statement_id=? AND idempotency_key=?",(rs,n)->rs.getLong(1),statementId,r.idempotencyKey());if(!old.isEmpty())return statement(statementId,null,true);if(st.getFirst()[1]+r.amountFen()>st.getFirst()[0])throw new ResponseStatusException(HttpStatus.CONFLICT,"Manual payments exceed statement total");insert("INSERT INTO settlement_payment_record(statement_id,idempotency_key,amount_fen,paid_on,reference_no,operation,note,actor) VALUES (?,?,?,?,?,'PAYMENT',?,?)",statementId,r.idempotencyKey(),r.amountFen(),r.paidOn(),r.referenceNo(),r.note(),actor);long paid=st.getFirst()[1]+r.amountFen();String status=paid==st.getFirst()[0]?"PAID":"PARTIALLY_PAID";db.update("UPDATE settlement_statement SET paid_amount_fen=?,status=? WHERE id=?",paid,status,statementId);if("PAID".equals(status))db.update("UPDATE supplier_ledger_entry SET status='PAID' WHERE id IN(SELECT ledger_entry_id FROM settlement_statement_item WHERE statement_id=?)",statementId);return statement(statementId,null,true);}
    @Transactional public Map<String,Object> reverse(long statementId,long paymentId,String key,String note,String actor){var st=db.query("SELECT paid_amount_fen FROM settlement_statement WHERE id=? FOR UPDATE",(rs,n)->rs.getLong(1),statementId);if(st.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var p=db.query("SELECT amount_fen,paid_on,reference_no FROM settlement_payment_record WHERE id=? AND statement_id=? AND operation='PAYMENT'",(rs,n)->new Object[]{rs.getLong(1),rs.getDate(2).toLocalDate(),rs.getString(3)},paymentId,statementId);if(p.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND);Integer reversed=db.queryForObject("SELECT COUNT(*) FROM settlement_payment_record WHERE reverses_payment_id=?",Integer.class,paymentId);if(reversed>0)return statement(statementId,null,true);insert("INSERT INTO settlement_payment_record(statement_id,idempotency_key,amount_fen,paid_on,reference_no,operation,reverses_payment_id,note,actor) VALUES (?,?,?,?,?,'REVERSAL',?,?,?)",statementId,key,p.getFirst()[0],LocalDate.now(),"REV-"+p.getFirst()[2],paymentId,note,actor);long paid=st.getFirst()-(long)p.getFirst()[0];db.update("UPDATE settlement_statement SET paid_amount_fen=?,status=? WHERE id=?",paid,paid==0?"UNPAID":"PARTIALLY_PAID",statementId);db.update("UPDATE supplier_ledger_entry SET status='IN_STATEMENT' WHERE status='PAID' AND id IN(SELECT ledger_entry_id FROM settlement_statement_item WHERE statement_id=?)",statementId);return statement(statementId,null,true);}
    @Transactional public void adjustment(AdjustmentRequest r,String actor){db.update("INSERT INTO supplier_ledger_entry(supplier_id,sales_order_id,entry_type,source_key,amount_fen,status,description) VALUES (?,?,?,?,?,'AVAILABLE',?)",r.supplierId(),r.orderId(),r.type(),"manual-adjustment:"+r.idempotencyKey(),r.amountFen(),r.reason()+"；操作人:"+actor);}
}
