package com.orchard.mall;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.env.MockEnvironment;
import org.springframework.test.context.TestPropertySource;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest
@TestPropertySource(properties={
 "spring.datasource.url=${PHASE3_TEST_DB_URL:jdbc:h2:mem:phase3;MODE=MySQL;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000}",
 "spring.datasource.username=${PHASE3_TEST_DB_USER:sa}","spring.datasource.password=${PHASE3_TEST_DB_PASSWORD:}",
 "spring.profiles.active=test","app.admin-init-password=long-test-password-123","app.dev-payment-enabled=true",
 "app.payment-merchant-subject=phase3-test-merchant","storage.access-key=test","storage.secret-key=test",
 "app.order-expiry-scan-ms=3600000","app.notification-scan-ms=3600000"
})
class Phase3FlowTest {
 @Autowired JdbcTemplate db;@Autowired PaymentService payments;@Autowired FulfillmentService fulfillment;@Autowired NotificationOutbox outbox;@Autowired ObjectMapper json;
 long consumer=301,supplier=301,supply=301;int sequence;
 @BeforeEach void seed(){
  db.update("DELETE FROM settlement_payment_record WHERE reverses_payment_id IS NOT NULL");
  for(String t:List.of("settlement_payment_record","settlement_statement_item","settlement_statement","supplier_ledger_entry","replacement_reservation","refund_ledger","refund_event","refund_attempt","refund_order","after_sale_operation","after_sale_evidence","after_sale_item","after_sale_case","parcel_operation_log","parcel_item","parcel","fulfillment_task_item","notification_outbox","fulfillment_task","payment_anomaly","payment_event","payment_attempt","payment_order","inventory_movement","stock_reservation","order_item","order_group","sales_order","supplier_session","supplier_user","supply_inventory","sku_supply","shipping_rule","shipping_template","sku","product_image","product","origin","supplier","category","consumer_session","consumer_identity","consumer_account"))db.update("DELETE FROM "+t);
  db.update("INSERT INTO consumer_account(id) VALUES (?)",consumer);db.update("INSERT INTO category(id,name,sort_order,enabled) VALUES (301,'测试',1,TRUE)");
  db.update("INSERT INTO supplier(id,name,contact_name,contact_phone,source_type,enabled) VALUES (?,'甲供应商','甲','13800000000','FARMER',TRUE)",supplier);
  db.update("INSERT INTO supplier(id,name,contact_name,contact_phone,source_type,enabled) VALUES (302,'乙供应商','乙','13900000000','FARMER',TRUE)");
  db.update("INSERT INTO origin(id,supplier_id,label,province,city,address) VALUES (301,301,'仓','陕','西安','仓址')");
  db.update("INSERT INTO product(id,category_id,title,description,published) VALUES (301,301,'苹果','',TRUE)");
  db.update("INSERT INTO sku(id,product_id,code,spec_json,retail_price_fen,net_weight_g,billable_weight_g,active) VALUES (301,301,'APPLE','{}',1000,500,500,TRUE)");
  db.update("INSERT INTO shipping_template(id,name,enabled,version) VALUES (301,'模板',TRUE,1)");
  db.update("INSERT INTO sku_supply(id,sku_id,supplier_id,origin_id,supply_price_fen,is_default,shipping_template_id) VALUES (301,301,301,301,500,TRUE,301)");
  db.update("INSERT INTO supply_inventory(supply_id,on_hand_qty,reserved_qty) VALUES (?,20,0)",supply);sequence=0;
 }
 long order(int quantity){long id=400+(++sequence);String no="P3-"+id;db.update("INSERT INTO sales_order(id,order_no,consumer_id,idempotency_key,request_hash,quote_hash,status,item_amount_fen,shipping_amount_fen,payable_amount_fen,recipient,mobile,province_code,province_name,city_code,city_name,district_code,district_name,address_detail,expires_at) VALUES (?,?,? ,?,'r','q','PENDING_PAYMENT',?,0,?,'收件人','13800000001','610000','陕西','610100','西安','610102','新城','地址',?)",id,no,consumer,"idem-"+id,quantity*1000,quantity*1000,java.time.LocalDateTime.now().plusHours(1));long group=500+sequence;long item=600+sequence;db.update("INSERT INTO order_group(id,order_id,supplier_id,supplier_name,origin_id,origin_label,origin_province,origin_city,origin_address,template_id,template_name,template_version,rule_region_code,billable_weight_g,item_amount_fen,shipping_fee_fen) VALUES (?,?,301,'甲供应商',301,'仓','陕','西安','仓址',301,'模板',1,'610000',?,?,0)",group,id,quantity*500,quantity*1000);db.update("INSERT INTO order_item(id,order_id,group_id,product_id,product_title,sku_id,sku_code,spec_json,quantity,unit_price_fen,line_amount_fen,net_weight_g,billable_weight_g,supply_id,supplier_id,origin_id,template_id) VALUES (?,?,?,301,'苹果',301,'APPLE','{}',?,1000,?,500,500,301,301,301,301)",item,id,group,quantity,quantity*1000);db.update("UPDATE supply_inventory SET reserved_qty=reserved_qty+? WHERE supply_id=?",quantity,supply);db.update("INSERT INTO stock_reservation(order_id,supply_id,quantity,status) VALUES (?,?,?,'HELD')",id,supply,quantity);return id;}
 PaymentService.AttemptView attempt(long order){return payments.create(consumer,order,"DEV_SIMULATOR");}
 PaymentAdapter.PaymentNotice notice(PaymentService.AttemptView a,String event,String status){return new PaymentAdapter.PaymentNotice(event,a.attemptNo(),status,"DEV-"+a.attemptNo(),a.amountFen(),"CNY","phase3-test-merchant");}

 @Test void queryAndNotificationConcurrentSuccessConvertsStockAndCreatesTasksOnce() throws Exception {long order=order(2);var a=attempt(order);try(var pool=Executors.newFixedThreadPool(2)){var f1=pool.submit(()->payments.processNotice("DEV_SIMULATOR",notice(a,"notification-event","SUCCESS")));var f2=pool.submit(()->payments.processNotice("DEV_SIMULATOR",notice(a,"query-event","SUCCESS")));f1.get();f2.get();}assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,order)).isEqualTo("PAID");assertThat(db.queryForObject("SELECT on_hand_qty FROM supply_inventory WHERE supply_id=?",Integer.class,supply)).isEqualTo(18);assertThat(db.queryForObject("SELECT reserved_qty FROM supply_inventory WHERE supply_id=?",Integer.class,supply)).isZero();assertThat(db.queryForObject("SELECT COUNT(*) FROM inventory_movement WHERE order_id=? AND reason='支付确认转已售'",Integer.class,order)).isOne();assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=?",Integer.class,order)).isOne();assertThat(db.queryForObject("SELECT COUNT(*) FROM notification_outbox",Integer.class)).isOne();assertThat(db.queryForObject("SELECT COUNT(*) FROM payment_anomaly",Integer.class)).isZero();}

 @Test void successWinsFromClosePendingAndNotificationRetryDoesNotCreateAnotherTask(){long order=order(1);var a=attempt(order);db.update("UPDATE sales_order SET status='CLOSE_PENDING',payment_status='CLOSE_PENDING' WHERE id=?",order);assertThat(payments.processNotice("DEV_SIMULATOR",notice(a,"success-during-close","SUCCESS")).status()).isEqualTo("SUCCESS");assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,order)).isEqualTo("PAID");db.update("UPDATE notification_outbox SET status='PENDING',attempt_count=2,last_error='simulated previous delivery failure',next_attempt_at=CURRENT_TIMESTAMP");outbox.scan();assertThat(db.queryForObject("SELECT status FROM notification_outbox",String.class)).isEqualTo("SENT");assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=?",Integer.class,order)).isOne();}

 @Test void paymentCancelAndTimeoutRacesKeepInventoryConsistent() throws Exception {long racing=order(1);var a=attempt(racing);try(var pool=Executors.newFixedThreadPool(2)){var success=pool.submit(()->payments.processNotice("DEV_SIMULATOR",notice(a,"race-success","SUCCESS")));var cancel=pool.submit(()->{payments.coordinateClose(consumer,racing,"CANCELLED");return null;});success.get();cancel.get();}String state=db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,racing);assertThat(state).isIn("PAID","CANCELLED");int sold=db.queryForObject("SELECT COUNT(*) FROM stock_reservation WHERE order_id=? AND status='SOLD'",Integer.class,racing);int released=db.queryForObject("SELECT COUNT(*) FROM stock_reservation WHERE order_id=? AND status='RELEASED'",Integer.class,racing);assertThat(sold+released).isOne();assertThat(db.queryForObject("SELECT reserved_qty FROM supply_inventory WHERE supply_id=?",Integer.class,supply)).isZero();assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=?",Integer.class,racing)).isEqualTo("PAID".equals(state)?1:0);long noAttempt=order(1);try(var pool=Executors.newFixedThreadPool(2)){var user=pool.submit(()->{payments.coordinateClose(consumer,noAttempt,"CANCELLED");return null;});var timeout=pool.submit(()->{payments.coordinateClose(null,noAttempt,"CLOSED");return null;});user.get();timeout.get();}assertThat(db.queryForObject("SELECT COUNT(*) FROM inventory_movement WHERE order_id=? AND delta_reserved=-1",Integer.class,noAttempt)).isOne();}

 @Test void identicalEventRetriesAfterTransactionFailureAndRestartRecovery() {long order=order(1);var a=attempt(order);var exact=notice(a,"same-event-same-payload","SUCCESS");db.update("UPDATE supply_inventory SET reserved_qty=0 WHERE supply_id=?",supply);assertThatThrownBy(()->payments.processNotice("DEV_SIMULATOR",exact)).isInstanceOf(IllegalStateException.class);assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,order)).isEqualTo("PENDING_PAYMENT");assertThat(db.queryForObject("SELECT processing_status FROM payment_event WHERE event_key='same-event-same-payload'",String.class)).isEqualTo("RECEIVED");db.update("UPDATE supply_inventory SET reserved_qty=1 WHERE supply_id=?",supply);db.update("UPDATE payment_event SET next_attempt_at=CURRENT_TIMESTAMP WHERE event_key='same-event-same-payload'");payments.recoverReceivedEvents();assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,order)).isEqualTo("PAID");assertThat(db.queryForObject("SELECT processing_status FROM payment_event WHERE event_key='same-event-same-payload'",String.class)).isEqualTo("PROCESSED");assertThat(payments.processNotice("DEV_SIMULATOR",exact).duplicate()).isTrue();assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=?",Integer.class,order)).isOne();assertThat(db.queryForObject("SELECT COUNT(*) FROM notification_outbox",Integer.class)).isOne();}

 @Test void paymentIdentityMismatchIsRejected(){long other=order(1);var b=attempt(other);var bad=new PaymentAdapter.PaymentNotice("bad-amount",b.attemptNo(),"SUCCESS","DEV-BAD",b.amountFen()+1,"CNY","phase3-test-merchant");assertThat(payments.processNotice("DEV_SIMULATOR",bad).status()).isEqualTo("REJECTED");assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,other)).isEqualTo("PENDING_PAYMENT");}

 @Test void closeUnknownDoesNotReleaseAndLateSuccessAfterConfirmedCloseBecomesAnomaly(){long unknownOrder=order(1);var unknownAttempt=attempt(unknownOrder);payments.processNotice("DEV_SIMULATOR",notice(unknownAttempt,"unknown","UNKNOWN"));payments.coordinateClose(consumer,unknownOrder,"CANCELLED");assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,unknownOrder)).isEqualTo("CLOSE_PENDING");assertThat(db.queryForObject("SELECT reserved_qty FROM supply_inventory WHERE supply_id=?",Integer.class,supply)).isEqualTo(1);long closedOrder=order(1);var closedAttempt=attempt(closedOrder);payments.coordinateClose(consumer,closedOrder,"CANCELLED");assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,closedOrder)).isEqualTo("CANCELLED");assertThat(payments.processNotice("DEV_SIMULATOR",notice(closedAttempt,"late-success","SUCCESS")).status()).isEqualTo("ANOMALY");assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE sales_order_id=?",Integer.class,closedOrder)).isZero();assertThat(db.queryForObject("SELECT anomaly_type FROM payment_anomaly",String.class)).isEqualTo("SUCCESS_AFTER_RELEASE");}

 @Test void partialShipmentIdempotencyCrossSupplierAndConcurrentOvershipProtection() throws Exception {long order=order(3);var a=attempt(order);payments.processNotice("DEV_SIMULATOR",notice(a,"ship-pay","SUCCESS"));long task=db.queryForObject("SELECT id FROM fulfillment_task WHERE sales_order_id=?",Long.class,order);long item=db.queryForObject("SELECT id FROM fulfillment_task_item WHERE task_id=?",Long.class,task);assertThatThrownBy(()->fulfillment.detail(task,302L)).isInstanceOf(org.springframework.web.server.ResponseStatusException.class);fulfillment.accept(task,supplier,"supplier:301:1");var one=new FulfillmentService.ParcelRequest("parcel-one", "SF","顺丰","SF001",List.of(new FulfillmentService.ParcelLine(item,1)));var first=fulfillment.createParcel(task,supplier,"SUPPLIER","supplier:301:1",one);assertThat(fulfillment.createParcel(task,supplier,"SUPPLIER","supplier:301:1",one).get("id")).isEqualTo(first.get("id"));assertThat(db.queryForObject("SELECT status FROM fulfillment_task WHERE id=?",String.class,task)).isEqualTo("PARTIALLY_SHIPPED");var tooMuch=new FulfillmentService.ParcelRequest("parcel-over", "SF","顺丰","SF002",List.of(new FulfillmentService.ParcelLine(item,3)));try(var pool=Executors.newFixedThreadPool(2)){var x=pool.submit(()->{try{fulfillment.createParcel(task,supplier,"SUPPLIER","s",tooMuch);return true;}catch(Exception e){return false;}});var y=pool.submit(()->{try{fulfillment.createParcel(task,supplier,"SUPPLIER","s",tooMuch);return true;}catch(Exception e){return false;}});assertThat(List.of(x.get(),y.get())).containsOnly(false);}var rest=new FulfillmentService.ParcelRequest("parcel-rest", "YT","圆通","YT001",List.of(new FulfillmentService.ParcelLine(item,2)));fulfillment.createParcel(task,supplier,"SUPPLIER","supplier:301:1",rest);assertThat(db.queryForObject("SELECT status FROM fulfillment_task WHERE id=?",String.class,task)).isEqualTo("SHIPPED");assertThat(db.queryForObject("SELECT fulfillment_status FROM sales_order WHERE id=?",String.class,order)).isEqualTo("SHIPPED");}

 @Test void productionCannotEnableSimulatorOrDevelopmentLogin(){var env=new MockEnvironment();env.setActiveProfiles("prod");assertThatThrownBy(()->new DevPaymentAdapter(env,json,db,true)).isInstanceOf(IllegalStateException.class).hasMessageContaining("forbidden");assertThatThrownBy(()->new ConsumerAuthController(db,env,true)).isInstanceOf(IllegalStateException.class).hasMessageContaining("forbidden");}
}
