package com.orchard.mall;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.env.MockEnvironment;
import org.springframework.test.context.TestPropertySource;
import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDate;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest
@TestPropertySource(properties={
 "spring.datasource.url=${PHASE4_TEST_DB_URL:jdbc:h2:mem:phase4;MODE=MySQL;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000}",
 "spring.datasource.username=${PHASE4_TEST_DB_USER:sa}","spring.datasource.password=${PHASE4_TEST_DB_PASSWORD:}",
 "spring.profiles.active=test","app.admin-init-password=long-test-password-123","app.dev-payment-enabled=true","app.dev-refund-enabled=true",
 "app.payment-merchant-subject=phase4-test-merchant","storage.access-key=test","storage.secret-key=test",
 "app.order-expiry-scan-ms=3600000","app.notification-scan-ms=3600000","app.payment-event-recovery-ms=3600000","app.refund-event-recovery-ms=3600000"
})
class Phase4FlowTest {
 @Autowired JdbcTemplate db;@Autowired PaymentService payments;@Autowired FulfillmentService fulfillment;@Autowired AfterSalesService afterSales;
 @Autowired RefundService refunds;@Autowired SettlementService settlements;@Autowired RefundProcessingFaultInjector refundFaults;@Autowired SupplierAuthController supplierAuth;@Autowired ObjectMapper json;
 long consumer=401,otherConsumer=402,supplier=401,otherSupplier=402,supply=401;int sequence;

 @BeforeEach void seed(){
  db.update("DELETE FROM settlement_payment_record WHERE reverses_payment_id IS NOT NULL");
  for(String t:List.of("settlement_payment_record","settlement_statement_item","settlement_statement","supplier_ledger_entry","replacement_reservation","refund_ledger","refund_event","refund_attempt","refund_order","after_sale_operation","after_sale_evidence","after_sale_item","after_sale_case","parcel_operation_log","parcel_item","parcel","fulfillment_task_item","notification_outbox","fulfillment_task","payment_anomaly","payment_event","payment_attempt","payment_order","inventory_movement","stock_reservation","order_item","order_group","sales_order","supplier_session","supplier_user","supply_inventory","sku_supply","shipping_rule","shipping_template","sku","product_image","product","origin","supplier","category","consumer_session","consumer_identity","consumer_account"))db.update("DELETE FROM "+t);
  db.update("INSERT INTO consumer_account(id) VALUES (?),(?)",consumer,otherConsumer);db.update("INSERT INTO category(id,name,sort_order,enabled) VALUES (401,'测试',1,TRUE)");
  db.update("INSERT INTO supplier(id,name,contact_name,contact_phone,source_type,enabled) VALUES (?,'甲供应商','甲','13800000000','FARMER',TRUE),(?,'乙供应商','乙','13900000000','FARMER',TRUE)",supplier,otherSupplier);
  db.update("INSERT INTO origin(id,supplier_id,label,province,city,address) VALUES (401,401,'仓','陕','西安','仓址')");db.update("INSERT INTO product(id,category_id,title,description,published) VALUES (401,401,'苹果','',TRUE)");
  db.update("INSERT INTO sku(id,product_id,code,spec_json,retail_price_fen,net_weight_g,billable_weight_g,active) VALUES (401,401,'APPLE','{}',1000,500,500,TRUE)");db.update("INSERT INTO shipping_template(id,name,enabled,version) VALUES (401,'模板',TRUE,1)");
  db.update("INSERT INTO sku_supply(id,sku_id,supplier_id,origin_id,supply_price_fen,is_default,shipping_template_id) VALUES (401,401,401,401,500,TRUE,401)");db.update("INSERT INTO supply_inventory(supply_id,on_hand_qty,reserved_qty) VALUES (?,30,0)",supply);sequence=0;
 }
 long order(int qty){long id=700+(++sequence),group=800+sequence,item=900+sequence;db.update("INSERT INTO sales_order(id,order_no,consumer_id,idempotency_key,request_hash,quote_hash,status,item_amount_fen,shipping_amount_fen,payable_amount_fen,recipient,mobile,province_code,province_name,city_code,city_name,district_code,district_name,address_detail,expires_at) VALUES (?,?,? ,?,'r','q','PENDING_PAYMENT',?,0,?,'收件人','13800000001','610000','陕西','610100','西安','610102','新城','地址',?)",id,"P4-"+id,consumer,"idem-"+id,qty*1000,qty*1000,java.time.LocalDateTime.now().plusHours(1));db.update("INSERT INTO order_group(id,order_id,supplier_id,supplier_name,origin_id,origin_label,origin_province,origin_city,origin_address,template_id,template_name,template_version,rule_region_code,billable_weight_g,item_amount_fen,shipping_fee_fen) VALUES (?,?,401,'甲供应商',401,'仓','陕','西安','仓址',401,'模板',1,'610000',?,?,0)",group,id,qty*500,qty*1000);db.update("INSERT INTO order_item(id,order_id,group_id,product_id,product_title,sku_id,sku_code,spec_json,quantity,unit_price_fen,line_amount_fen,net_weight_g,billable_weight_g,supply_id,supply_price_fen,supplier_id,origin_id,template_id) VALUES (?,?,?,401,'苹果',401,'APPLE','{}',?,1000,?,500,500,401,500,401,401,401)",item,id,group,qty,qty*1000);db.update("UPDATE supply_inventory SET reserved_qty=reserved_qty+? WHERE supply_id=?",qty,supply);db.update("INSERT INTO stock_reservation(order_id,supply_id,quantity,status) VALUES (?,?,?,'HELD')",id,supply,qty);return id;}
 long paid(int qty){long o=order(qty);var a=payments.create(consumer,o,"DEV_SIMULATOR");payments.processNotice("DEV_SIMULATOR",new PaymentAdapter.PaymentNotice("pay-"+o,a.attemptNo(),"SUCCESS","TX-"+o,a.amountFen(),"CNY","phase4-test-merchant"));return o;}
 long item(long o){return db.queryForObject("SELECT id FROM order_item WHERE order_id=?",Long.class,o);}long task(long o,String type){return db.queryForObject("SELECT id FROM fulfillment_task WHERE sales_order_id=? AND task_type=?",Long.class,o,type);}long taskItem(long t){return db.queryForObject("SELECT id FROM fulfillment_task_item WHERE task_id=?",Long.class,t);}
 long apply(long o,String action,int qty){return ((Number)afterSales.apply(consumer,o,new AfterSalesService.ApplyRequest(action,"DAMAGED","test",List.of(new AfterSalesService.ApplyItem(item(o),qty)),null)).get("id")).longValue();}
 RefundService.RefundView approveRefund(long c,long amount){var ai=db.queryForObject("SELECT id FROM after_sale_item WHERE case_id=?",Long.class,c);var out=afterSales.review(c,"admin",new AfterSalesService.ReviewRequest("APPROVE","approved",amount,0L,"MERCHANT",0L,"DEV_SIMULATOR",List.of(new AfterSalesService.ReviewItem(ai,1))));return refunds.createForCase(c,out.shippingRefundFen(),"DEV_SIMULATOR","admin");}
 RefundAdapter.RefundNotice refundNotice(RefundService.RefundView r,String event,String status){return new RefundAdapter.RefundNotice(event,r.channelRequestNo(),status,"DEV-RF-TX-"+r.id(),r.amountFen(),r.currency());}

 @Test void parcelReceiptIsOwnedIdempotentAndUnlocksSnapshotLedger(){long o=paid(1),t=task(o,"ORIGINAL"),ti=taskItem(t);fulfillment.accept(t,supplier,"supplier:401:1");var p=fulfillment.createParcel(t,supplier,"SUPPLIER","supplier:401:1",new FulfillmentService.ParcelRequest("receipt-key","SF","顺丰","SF-R",List.of(new FulfillmentService.ParcelLine(ti,1))));long parcel=((Number)p.get("id")).longValue();assertThatThrownBy(()->fulfillment.confirmReceived(parcel,otherConsumer)).isInstanceOf(ResponseStatusException.class);fulfillment.confirmReceived(parcel,consumer);fulfillment.confirmReceived(parcel,consumer);assertThat(db.queryForObject("SELECT COUNT(*) FROM parcel WHERE id=? AND received_at IS NOT NULL",Integer.class,parcel)).isOne();assertThat(db.queryForObject("SELECT completion_status FROM sales_order WHERE id=?",String.class,o)).isEqualTo("COMPLETED");assertThat(db.queryForObject("SELECT status FROM supplier_ledger_entry WHERE source_key=?",String.class,"goods:"+item(o))).isEqualTo("AVAILABLE");}

 @Test void refundApplicationUsesExplicitProductAmountWithinCapturedLinePrice(){long o=paid(1);var line=List.of(new AfterSalesService.ApplyItem(item(o),1));db.update("UPDATE store_settings SET contact_phone='01012345678' WHERE id=1");assertThat(afterSales.eligibility(consumer,o,item(o)).get("maxRefundFen")).isEqualTo(1000L);long c=((Number)afterSales.apply(consumer,o,new AfterSalesService.ApplyRequest("REFUND","BAD_FRUIT","partial",line,500L)).get("id")).longValue();assertThat(db.queryForObject("SELECT requested_refund_fen FROM after_sale_case WHERE id=?",Long.class,c)).isEqualTo(500L);assertThat(afterSales.eligibility(consumer,o,item(o)).get("maxRefundFen")).isEqualTo(0L);assertThat(afterSales.eligibility(consumer,o,item(o)).get("reason")).asString().contains("仅支持一次");assertThat(afterSales.eligibility(consumer,o,item(o)).get("storeContactPhone")).isEqualTo("01012345678");long another=paid(1);var anotherLine=List.of(new AfterSalesService.ApplyItem(item(another),1));for(long amount:List.of(0L,-1L,1001L))assertThatThrownBy(()->afterSales.apply(consumer,another,new AfterSalesService.ApplyRequest("REFUND","BAD_FRUIT","invalid",anotherLine,amount))).isInstanceOf(ResponseStatusException.class);assertThat(db.queryForObject("SELECT COUNT(*) FROM after_sale_case WHERE sales_order_id=?",Integer.class,another)).isZero();}

 @Test void reviewCannotExceedRequestedAmountOrCurrentCollectedBalance(){long o=paid(1);long c=((Number)afterSales.apply(consumer,o,new AfterSalesService.ApplyRequest("REFUND","BAD_FRUIT","partial",List.of(new AfterSalesService.ApplyItem(item(o),1)),500L)).get("id")).longValue();long ai=db.queryForObject("SELECT id FROM after_sale_item WHERE case_id=?",Long.class,c);var lines=List.of(new AfterSalesService.ReviewItem(ai,1));assertThatThrownBy(()->afterSales.review(c,"admin",new AfterSalesService.ReviewRequest("APPROVE","too much",600L,0L,"MERCHANT",0L,"DEV_SIMULATOR",lines))).isInstanceOf(ResponseStatusException.class);long pay=db.queryForObject("SELECT id FROM payment_order WHERE sales_order_id=?",Long.class,o);db.update("INSERT INTO refund_order(refund_no,channel_request_no,payment_order_id,amount_fen,shipping_amount_fen,currency,status,reason,created_by) VALUES ('P4-OCCUPIED','P4-OCCUPIED-REQ',?,600,0,'CNY','PENDING','test','test')",pay);assertThatThrownBy(()->afterSales.review(c,"admin",new AfterSalesService.ReviewRequest("APPROVE","balance",500L,0L,"MERCHANT",0L,"DEV_SIMULATOR",lines))).isInstanceOf(ResponseStatusException.class);assertThat(db.queryForObject("SELECT status FROM after_sale_case WHERE id=?",String.class,c)).isEqualTo("SUBMITTED");}

 @Test void unshippedRefundFreezesShipmentRestoresOnlyCancelledStockAndUnknownOccupiesMoney(){long o=paid(2),t=task(o,"ORIGINAL"),ti=taskItem(t),before=db.queryForObject("SELECT on_hand_qty FROM supply_inventory WHERE supply_id=?",Long.class,supply);long c=apply(o,"REFUND",1);assertThatThrownBy(()->fulfillment.createParcel(t,null,"ADMIN","admin",new FulfillmentService.ParcelRequest("frozen-ship","SF","顺丰","SF-F",List.of(new FulfillmentService.ParcelLine(ti,2))))).isInstanceOf(ResponseStatusException.class);db.update("UPDATE origin SET enabled=FALSE WHERE id=401");var r=approveRefund(c,1000);assertThat(db.queryForObject("SELECT cancelled_qty FROM fulfillment_task_item WHERE id=?",Integer.class,ti)).isOne();assertThat(db.queryForObject("SELECT on_hand_qty FROM supply_inventory WHERE supply_id=?",Long.class,supply)).isEqualTo(before+1);refunds.processNotice("DEV_SIMULATOR",refundNotice(r,"unknown-refund","UNKNOWN"));assertThat(refunds.createForCase(c,0,"DEV_SIMULATOR","admin").attemptNo()).isEqualTo(r.attemptNo());assertThat(db.queryForObject("SELECT COUNT(*) FROM refund_order WHERE payment_order_id=(SELECT id FROM payment_order WHERE sales_order_id=?)",Integer.class,o)).isOne();}

 @Test void concurrentRefundsStayWithinCapturedPaymentAndLineQuantity() throws Exception {long o=paid(2),c1=apply(o,"REFUND",1),c2=apply(o,"REFUND",1);assertThatThrownBy(()->apply(o,"REFUND",1)).isInstanceOf(ResponseStatusException.class);for(long c:List.of(c1,c2)){long ai=db.queryForObject("SELECT id FROM after_sale_item WHERE case_id=?",Long.class,c);afterSales.review(c,"admin",new AfterSalesService.ReviewRequest("APPROVE","parallel",1000L,0L,"MERCHANT",0L,"DEV_SIMULATOR",List.of(new AfterSalesService.ReviewItem(ai,1))));}try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->refunds.createForCase(c1,0,"DEV_SIMULATOR","admin"));var b=pool.submit(()->refunds.createForCase(c2,0,"DEV_SIMULATOR","admin"));a.get();b.get();}long collected=db.queryForObject("SELECT amount_fen FROM payment_order WHERE sales_order_id=?",Long.class,o);long occupied=db.queryForObject("SELECT SUM(amount_fen) FROM refund_order WHERE payment_order_id=(SELECT id FROM payment_order WHERE sales_order_id=?) AND status IN ('PENDING','UNKNOWN','SUCCEEDED')",Long.class,o);assertThat(occupied).isEqualTo(collected);assertThat(db.queryForObject("SELECT COUNT(*) FROM refund_order WHERE payment_order_id=(SELECT id FROM payment_order WHERE sales_order_id=?)",Integer.class,o)).isEqualTo(2);assertThatThrownBy(()->afterSales.detail(c1,null,false,otherSupplier)).isInstanceOf(ResponseStatusException.class);}

 @Test void shippedDamageRefundNeverRestoresInventoryAndDuplicateSuccessBooksOnce(){long o=paid(1),t=task(o,"ORIGINAL"),ti=taskItem(t);fulfillment.accept(t,supplier,"s");fulfillment.createParcel(t,supplier,"SUPPLIER","s",new FulfillmentService.ParcelRequest("damage-ship","SF","顺丰","SF-D",List.of(new FulfillmentService.ParcelLine(ti,1))));long before=db.queryForObject("SELECT on_hand_qty FROM supply_inventory WHERE supply_id=?",Long.class,supply);long c=apply(o,"REFUND",1);var r=approveRefund(c,600);var n=refundNotice(r,"refund-success","SUCCESS");assertThat(refunds.processNotice("DEV_SIMULATOR",n).status()).isEqualTo("SUCCESS");assertThat(refunds.processNotice("DEV_SIMULATOR",n).duplicate()).isTrue();assertThat(db.queryForObject("SELECT on_hand_qty FROM supply_inventory WHERE supply_id=?",Long.class,supply)).isEqualTo(before);assertThat(db.queryForObject("SELECT COUNT(*) FROM refund_ledger WHERE refund_order_id=?",Integer.class,r.id())).isOne();assertThat(db.queryForObject("SELECT status FROM sales_order WHERE id=?",String.class,o)).isEqualTo("PAID");}

 @Test void identicalRefundEventRetriesAfterBusinessTransactionFailure(){long o=paid(1),c=apply(o,"REFUND",1);var r=approveRefund(c,1000);var exact=refundNotice(r,"same-refund-event","SUCCESS");refundFaults.failNext(exact.eventKey());assertThatThrownBy(()->refunds.processNotice("DEV_SIMULATOR",exact)).isInstanceOf(IllegalStateException.class);assertThat(db.queryForObject("SELECT processing_status FROM refund_event WHERE event_key=?",String.class,exact.eventKey())).isEqualTo("RECEIVED");assertThat(db.queryForObject("SELECT COUNT(*) FROM refund_ledger WHERE refund_order_id=?",Integer.class,r.id())).isZero();db.update("UPDATE refund_event SET next_attempt_at=CURRENT_TIMESTAMP WHERE event_key=?",exact.eventKey());refunds.recover();assertThat(db.queryForObject("SELECT processing_status FROM refund_event WHERE event_key=?",String.class,exact.eventKey())).isEqualTo("PROCESSED");assertThat(db.queryForObject("SELECT COUNT(*) FROM refund_ledger WHERE refund_order_id=?",Integer.class,r.id())).isOne();assertThat(refunds.processNotice("DEV_SIMULATOR",exact).duplicate()).isTrue();}

 @Test void replacementIsIdempotentByReviewAndProtectsReservedStock(){long o=paid(1),t=task(o,"ORIGINAL"),ti=taskItem(t);fulfillment.accept(t,supplier,"s");fulfillment.createParcel(t,supplier,"SUPPLIER","s",new FulfillmentService.ParcelRequest("replace-ship","SF","顺丰","SF-X",List.of(new FulfillmentService.ParcelLine(ti,1))));long c=apply(o,"REPLACEMENT",1),ai=db.queryForObject("SELECT id FROM after_sale_item WHERE case_id=?",Long.class,c);var review=new AfterSalesService.ReviewRequest("APPROVE","reship",0L,0L,"SUPPLIER",0L,null,List.of(new AfterSalesService.ReviewItem(ai,1)));afterSales.review(c,"admin",review);assertThatThrownBy(()->afterSales.review(c,"admin",review)).isInstanceOf(ResponseStatusException.class);long rt=task(o,"REPLACEMENT");assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE source_key=?",Integer.class,"AFTER_SALE:"+c)).isOne();long rti=taskItem(rt);fulfillment.accept(rt,supplier,"s");long parcel=((Number)fulfillment.createParcel(rt,supplier,"SUPPLIER","s",new FulfillmentService.ParcelRequest("replace-parcel","SF","顺丰","SF-REP",List.of(new FulfillmentService.ParcelLine(rti,1)))).get("id")).longValue();assertThat(db.queryForObject("SELECT status FROM replacement_reservation WHERE after_sale_case_id=?",String.class,c)).isEqualTo("CONSUMED");assertThat(db.queryForObject("SELECT COUNT(*) FROM supplier_ledger_entry WHERE source_key=?",Integer.class,"replacement-cost:"+c)).isOne();fulfillment.confirmReceived(parcel,consumer);assertThat(db.queryForObject("SELECT status FROM after_sale_case WHERE id=?",String.class,c)).isEqualTo("COMPLETED");assertThat(db.queryForObject("SELECT after_sales_status FROM sales_order WHERE id=?",String.class,o)).isEqualTo("CLOSED");}
 @Test void disabledOriginalOriginLeavesReplacementWaitingWithExplicitReason(){long o=paid(1);long c=apply(o,"REPLACEMENT",1),ai=db.queryForObject("SELECT id FROM after_sale_item WHERE case_id=?",Long.class,c);db.update("UPDATE origin SET enabled=FALSE WHERE id=401");var outcome=afterSales.review(c,"admin",new AfterSalesService.ReviewRequest("APPROVE","reship",0L,0L,"SUPPLIER",0L,null,List.of(new AfterSalesService.ReviewItem(ai,1))));assertThat(outcome.status()).isEqualTo("WAITING_STOCK");assertThat(outcome.reason()).contains("已停用").contains("未自动切换供应商");assertThat(db.queryForObject("SELECT COUNT(*) FROM fulfillment_task WHERE source_key=?",Integer.class,"AFTER_SALE:"+c)).isZero();}

 @Test void settlementLocksEntriesSupportsPartialPaymentIdempotencyAndAppendOnlyReversal(){long o=paid(1),t=task(o,"ORIGINAL"),ti=taskItem(t);fulfillment.accept(t,supplier,"s");long parcel=((Number)fulfillment.createParcel(t,supplier,"SUPPLIER","s",new FulfillmentService.ParcelRequest("settle-ship","SF","顺丰","SF-S",List.of(new FulfillmentService.ParcelLine(ti,1)))).get("id")).longValue();fulfillment.confirmReceived(parcel,consumer);long ledger=db.queryForObject("SELECT id FROM supplier_ledger_entry WHERE source_key=?",Long.class,"goods:"+item(o));var st=settlements.createStatement(new SettlementService.StatementRequest(supplier,List.of(ledger)),"admin");long sid=((Number)st.get("id")).longValue();assertThatThrownBy(()->settlements.createStatement(new SettlementService.StatementRequest(supplier,List.of(ledger)),"admin")).isInstanceOf(ResponseStatusException.class);var pay=new SettlementService.PaymentRequest("manual-pay-1",250,LocalDate.now(),"BANK-MANUAL-1","人工登记，未校验银行流水");settlements.recordPayment(sid,pay,"admin");settlements.recordPayment(sid,pay,"admin");assertThat(db.queryForObject("SELECT COUNT(*) FROM settlement_payment_record WHERE statement_id=? AND operation='PAYMENT'",Integer.class,sid)).isOne();settlements.recordPayment(sid,new SettlementService.PaymentRequest("manual-pay-2",250,LocalDate.now(),"BANK-MANUAL-2",null),"admin");long payment=db.queryForObject("SELECT id FROM settlement_payment_record WHERE statement_id=? AND idempotency_key='manual-pay-2'",Long.class,sid);settlements.reverse(sid,payment,"reverse-pay-2","录入错误","admin");assertThat(db.queryForObject("SELECT status FROM settlement_statement WHERE id=?",String.class,sid)).isEqualTo("PARTIALLY_PAID");assertThat(db.queryForObject("SELECT status FROM supplier_ledger_entry WHERE id=?",String.class,ledger)).isEqualTo("IN_STATEMENT");settlements.adjustment(new SettlementService.AdjustmentRequest(supplier,o,"OTHER_ADJUSTMENT",-30,"已付款后售后差额","adjust-after-paid"),"admin");assertThat(db.queryForObject("SELECT amount_fen FROM supplier_ledger_entry WHERE source_key='manual-adjustment:adjust-after-paid'",Long.class)).isEqualTo(-30);}

 @Test void productionCannotEnableRefundSimulator(){var env=new MockEnvironment();env.setActiveProfiles("prod");assertThatThrownBy(()->new DevRefundAdapter(env,json,db,true)).isInstanceOf(IllegalStateException.class).hasMessageContaining("forbidden");}

 @Test void supplierPasswordResetAndDisableInvalidateServerSessions(){supplierAuth.create(new SupplierAuthController.Account(supplier,"supplier-phase4","initial-pass-123",true));long user=db.queryForObject("SELECT id FROM supplier_user WHERE username='supplier-phase4'",Long.class);supplierAuth.login(new SupplierAuthController.Login("supplier-phase4","initial-pass-123"));assertThat(db.queryForObject("SELECT COUNT(*) FROM supplier_session WHERE supplier_user_id=?",Integer.class,user)).isOne();supplierAuth.update(user,new SupplierAuthController.Account(supplier,"supplier-phase4","replacement-pass-456",true));assertThat(db.queryForObject("SELECT COUNT(*) FROM supplier_session WHERE supplier_user_id=?",Integer.class,user)).isZero();assertThatThrownBy(()->supplierAuth.login(new SupplierAuthController.Login("supplier-phase4","initial-pass-123"))).isInstanceOf(ResponseStatusException.class);supplierAuth.login(new SupplierAuthController.Login("supplier-phase4","replacement-pass-456"));supplierAuth.update(user,new SupplierAuthController.Account(supplier,"supplier-phase4",null,false));assertThat(db.queryForObject("SELECT COUNT(*) FROM supplier_session WHERE supplier_user_id=?",Integer.class,user)).isZero();assertThatThrownBy(()->supplierAuth.login(new SupplierAuthController.Login("supplier-phase4","replacement-pass-456"))).isInstanceOf(ResponseStatusException.class);}
}
